// <auto-generated />
using System;
using System.Collections.Generic;
using GuildSaber.Database.Contexts.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace GuildSaber.Database.Contexts.Server.Migrations
{
    [DbContext(typeof(ServerDbContext))]
    partial class ServerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CategoryRankedMap", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("integer");

                    b.Property<long>("RankedMapId")
                        .HasColumnType("bigint");

                    b.HasKey("CategoriesId", "RankedMapId");

                    b.HasIndex("RankedMapId");

                    b.ToTable("CategoryRankedMap");
                });

            modelBuilder.Entity("ContextPoint", b =>
                {
                    b.Property<int>("ContextId")
                        .HasColumnType("integer");

                    b.Property<int>("PointsId")
                        .HasColumnType("integer");

                    b.HasKey("ContextId", "PointsId");

                    b.HasIndex("PointsId");

                    b.ToTable("ContextPoint");
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.Auth.Session", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Browser")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BrowserVersion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.HasKey("SessionId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.Guilds.Boosts.Boost", b =>
                {
                    b.Property<int>("GuildId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("GuildId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Boosts");
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.Guilds.Categories.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GuildId")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Info", "GuildSaber.Database.Models.Server.Guilds.Categories.Category.Info#CategoryInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");
                        });

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.Guilds.Context", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GuildId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Info", "GuildSaber.Database.Models.Server.Guilds.Context.Info#ContextInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("Info_Description");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("Info_Name");
                        });

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("Contexts");
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.Guilds.ContextMember", b =>
                {
                    b.Property<int>("GuildId")
                        .HasColumnType("integer");

                    b.Property<int>("ContextId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.HasKey("GuildId", "ContextId", "PlayerId");

                    b.HasIndex("ContextId");

                    b.HasIndex("GuildId", "PlayerId");

                    b.ToTable("ContextMembers");
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.Guilds.Guild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "DiscordInfo", "GuildSaber.Database.Models.Server.Guilds.Guild.DiscordInfo#GuildDiscordInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal?>("MainDiscordGuildId")
                                .HasColumnType("numeric(20,0)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Info", "GuildSaber.Database.Models.Server.Guilds.Guild.Info#GuildInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Color")
                                .HasColumnType("integer");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("Info_CreatedAt");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("SmallName")
                                .IsRequired()
                                .HasMaxLength(6)
                                .HasColumnType("character varying(6)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Requirements", "GuildSaber.Database.Models.Server.Guilds.Guild.Requirements#GuildRequirements", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int?>("AccountAgeUnix")
                                .HasColumnType("integer")
                                .HasColumnName("Requirements_AccountAgeUnix");

                            b1.Property<int?>("MaxPP")
                                .HasColumnType("integer")
                                .HasColumnName("Requirements_MaxPP");

                            b1.Property<int?>("MaxRank")
                                .HasColumnType("integer")
                                .HasColumnName("Requirements_MaxRank");

                            b1.Property<int?>("MinPP")
                                .HasColumnType("integer")
                                .HasColumnName("Requirements_MinPP");

                            b1.Property<int?>("MinRank")
                                .HasColumnType("integer")
                                .HasColumnName("Requirements_MinRank");

                            b1.Property<bool>("RequireSubmission")
                                .HasColumnType("boolean")
                                .HasColumnName("Requirements_RequireSubmission");
                        });

                    b.HasKey("Id");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.Guilds.Levels.Level", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("ContextId")
                        .HasColumnType("integer");

                    b.Property<int>("GuildId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsLocking")
                        .HasColumnType("boolean");

                    b.Property<long>("Order")
                        .HasColumnType("bigint");

                    b.Property<byte>("Type")
                        .HasColumnType("smallint");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Info", "GuildSaber.Database.Models.Server.Guilds.Levels.Level.Info#LevelInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Color")
                                .HasColumnType("integer");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("Info_Name");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ContextId");

                    b.HasIndex("GuildId", "ContextId", "CategoryId");

                    b.ToTable("Levels");

                    b.HasDiscriminator<byte>("Type").IsComplete(true);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.Guilds.Members.Member", b =>
                {
                    b.Property<int>("GuildId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EditedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("JoinState")
                        .HasColumnType("integer");

                    b.Property<int>("Permissions")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.HasKey("GuildId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.Guilds.Members.MemberLevelStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContextId")
                        .HasColumnType("integer");

                    b.Property<int>("GuildId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<int>("LevelId")
                        .HasColumnType("integer");

                    b.Property<int?>("PassCount")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("ContextId", "PlayerId");

                    b.HasIndex("GuildId", "ContextId", "PlayerId", "LevelId")
                        .IsUnique();

                    b.ToTable("MemberLevelStats");
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.Guilds.Members.MemberPointStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("ContextId")
                        .HasColumnType("integer");

                    b.Property<int>("GuildId")
                        .HasColumnType("integer");

                    b.Property<int>("PassCount")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("PointId")
                        .HasColumnType("integer");

                    b.Property<float>("Points")
                        .HasColumnType("real");

                    b.Property<float>("Xp")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PointId");

                    b.HasIndex("ContextId", "PointId", "CategoryId");

                    b.HasIndex("GuildId", "ContextId", "PlayerId", "PointId", "CategoryId")
                        .IsUnique();

                    b.ToTable("MemberPointStats");
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.Guilds.Points.Point", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GuildId")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CurveSettings", "GuildSaber.Database.Models.Server.Guilds.Points.Point.CurveSettings#CurveSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<NpgsqlPoint[]>("Accuracy")
                                .IsRequired()
                                .HasColumnType("point[]");

                            b1.Property<NpgsqlPoint[]>("Difficulty")
                                .IsRequired()
                                .HasColumnType("point[]");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Info", "GuildSaber.Database.Models.Server.Guilds.Points.Point.Info#PointInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(6)
                                .HasColumnType("character varying(6)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ModifierValues", "GuildSaber.Database.Models.Server.Guilds.Points.Point.ModifierValues#ModifierValues", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<float>("BatteryEnergy")
                                .HasColumnType("real")
                                .HasColumnName("ModifierValues_BatteryEnergy");

                            b1.Property<float>("DisappearingArrows")
                                .HasColumnType("real")
                                .HasColumnName("ModifierValues_DisappearingArrows");

                            b1.Property<float>("FasterSong")
                                .HasColumnType("real")
                                .HasColumnName("ModifierValues_FasterSong");

                            b1.Property<float>("GhostNotes")
                                .HasColumnType("real")
                                .HasColumnName("ModifierValues_GhostNotes");

                            b1.Property<float>("InstaFail")
                                .HasColumnType("real")
                                .HasColumnName("ModifierValues_InstaFail");

                            b1.Property<float>("NoArrows")
                                .HasColumnType("real")
                                .HasColumnName("ModifierValues_NoArrows");

                            b1.Property<float>("NoBombs")
                                .HasColumnType("real")
                                .HasColumnName("ModifierValues_NoBombs");

                            b1.Property<float>("NoFail")
                                .HasColumnType("real")
                                .HasColumnName("ModifierValues_NoFail");

                            b1.Property<float>("NoObstacles")
                                .HasColumnType("real")
                                .HasColumnName("ModifierValues_NoObstacles");

                            b1.Property<float>("OffPlatform")
                                .HasColumnType("real")
                                .HasColumnName("ModifierValues_OffPlatform");

                            b1.Property<float>("OldDots")
                                .HasColumnType("real")
                                .HasColumnName("ModifierValues_OldDots");

                            b1.Property<float>("ProMode")
                                .HasColumnType("real")
                                .HasColumnName("ModifierValues_ProMode");

                            b1.Property<float>("SlowerSong")
                                .HasColumnType("real")
                                .HasColumnName("ModifierValues_SlowerSong");

                            b1.Property<float>("SmallNotes")
                                .HasColumnType("real")
                                .HasColumnName("ModifierValues_SmallNotes");

                            b1.Property<float>("StrictAngles")
                                .HasColumnType("real")
                                .HasColumnName("ModifierValues_StrictAngles");

                            b1.Property<float>("SuperFastSong")
                                .HasColumnType("real")
                                .HasColumnName("ModifierValues_SuperFastSong");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "WeightingSettings", "GuildSaber.Database.Models.Server.Guilds.Points.Point.WeightingSettings#WeightingSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool>("IsEnabled")
                                .HasColumnType("boolean")
                                .HasColumnName("WeightingSettings_IsEnabled");

                            b1.Property<double>("Multiplier")
                                .HasColumnType("double precision")
                                .HasColumnName("WeightingSettings_Multiplier");

                            b1.Property<int?>("TopScoreCountToConsider")
                                .HasColumnType("integer")
                                .HasColumnName("WeightingSettings_TopScoreCountToConsider");
                        });

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("Points");
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.Players.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsManager")
                        .HasColumnType("boolean");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "HardwareInfo", "GuildSaber.Database.Models.Server.Players.Player.HardwareInfo#PlayerHardwareInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("HMD")
                                .HasColumnType("integer")
                                .HasColumnName("HardwareInfo_HMD");

                            b1.Property<int>("Platform")
                                .HasColumnType("integer")
                                .HasColumnName("HardwareInfo_Platform");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Info", "GuildSaber.Database.Models.Server.Players.Player.Info#PlayerInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("AvatarUrl")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Info_AvatarUrl");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Info_Country");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("Info_CreatedAt");

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Info_Username");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "LinkedAccounts", "GuildSaber.Database.Models.Server.Players.Player.LinkedAccounts#PlayerLinkedAccounts", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("BeatLeaderId")
                                .HasColumnType("numeric(20,0)");

                            b1.Property<decimal?>("DiscordId")
                                .HasColumnType("numeric(20,0)");

                            b1.Property<decimal?>("ScoreSaberId")
                                .HasColumnType("numeric(20,0)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "SubscriptionInfo", "GuildSaber.Database.Models.Server.Players.Player.SubscriptionInfo#PlayerSubscriptionInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Tier")
                                .HasColumnType("integer")
                                .HasColumnName("SubscriptionInfo_Tier");
                        });

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.RankedMaps.MapVersions.MapVersion", b =>
                {
                    b.Property<long>("RankedMapId")
                        .HasColumnType("bigint");

                    b.Property<long>("SongDifficultyId")
                        .HasColumnType("bigint");

                    b.Property<int>("PlayModeId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("Order")
                        .HasColumnType("smallint");

                    b.Property<int>("SongId")
                        .HasColumnType("integer");

                    b.HasKey("RankedMapId", "SongDifficultyId", "PlayModeId");

                    b.HasIndex("PlayModeId");

                    b.HasIndex("SongDifficultyId");

                    b.HasIndex("SongId");

                    b.ToTable("MapVersions");
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.RankedMaps.MapVersions.PlayModes.PlayMode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("PlayModes");
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.RankedMaps.RankedMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ContextId")
                        .HasColumnType("integer");

                    b.Property<int>("GuildId")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Info", "GuildSaber.Database.Models.Server.RankedMaps.RankedMap.Info#RankedMapInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("Info_CreatedAt");

                            b1.Property<DateTimeOffset>("EditedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("Info_EditedAt");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Rating", "GuildSaber.Database.Models.Server.RankedMaps.RankedMap.Rating#RankedMapRating", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<float>("AccStar")
                                .HasColumnType("real");

                            b1.Property<float>("DiffStar")
                                .HasColumnType("real");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Requirements", "GuildSaber.Database.Models.Server.RankedMaps.RankedMap.Requirements#RankedMapRequirements", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("MandatoryModifiers")
                                .HasColumnType("integer")
                                .HasColumnName("Requirements_MandatoryModifiers");

                            b1.Property<float?>("MaxPauseDurationSec")
                                .HasColumnType("real")
                                .HasColumnName("Requirements_MaxPauseDurationSec");

                            b1.Property<float?>("MinAccuracy")
                                .HasColumnType("real");

                            b1.Property<bool>("NeedConfirmation")
                                .HasColumnType("boolean")
                                .HasColumnName("Requirements_NeedConfirmation");

                            b1.Property<bool>("NeedFullCombo")
                                .HasColumnType("boolean")
                                .HasColumnName("Requirements_NeedFullCombo");

                            b1.Property<int>("ProhibitedModifiers")
                                .HasColumnType("integer")
                                .HasColumnName("Requirements_ProhibitedModifiers");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ContextId");

                    b.HasIndex("GuildId");

                    b.ToTable("RankedMaps");
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.RankedScores.RankedScore", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ContextId")
                        .HasColumnType("integer");

                    b.Property<int>("DenyReason")
                        .HasColumnType("integer");

                    b.Property<int>("EffectiveScore")
                        .HasColumnType("integer");

                    b.Property<int>("GuildId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("PointId")
                        .HasColumnType("integer");

                    b.Property<int?>("PrevScoreId")
                        .HasColumnType("integer");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<long>("RankedMapId")
                        .HasColumnType("bigint");

                    b.Property<float>("RawPoints")
                        .HasColumnType("real");

                    b.Property<int>("ScoreId")
                        .HasColumnType("integer");

                    b.Property<long>("SongDifficultyId")
                        .HasColumnType("bigint");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PointId");

                    b.HasIndex("PrevScoreId");

                    b.HasIndex("RankedMapId");

                    b.HasIndex("ScoreId");

                    b.HasIndex("SongDifficultyId");

                    b.HasIndex("ContextId", "PointId", "RankedMapId");

                    b.ToTable("RankedScores");
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.Scores.AbstractScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BadCuts")
                        .HasColumnType("integer");

                    b.Property<int>("BaseScore")
                        .HasColumnType("integer");

                    b.Property<int>("HMD")
                        .HasColumnType("integer");

                    b.Property<bool>("IsFullCombo")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxCombo")
                        .HasColumnType("integer");

                    b.Property<int>("MissedNotes")
                        .HasColumnType("integer");

                    b.Property<int>("Modifiers")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("SetAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SongDifficultyId")
                        .HasColumnType("bigint");

                    b.Property<byte>("Type")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SongDifficultyId");

                    b.ToTable("Scores");

                    b.HasDiscriminator<byte>("Type").IsComplete(true);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.Songs.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BeatSaverKey")
                        .HasColumnType("text");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character(40)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Info", "GuildSaber.Database.Models.Server.Songs.Song.Info#SongInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("BeatSaverName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Info_BeatSaverName");

                            b1.Property<string>("MapperName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Info_MapperName");

                            b1.Property<string>("SongAuthorName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Info_SongAuthorName");

                            b1.Property<string>("SongName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Info_SongName");

                            b1.Property<string>("SongSubName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Info_SongSubName");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Stats", "GuildSaber.Database.Models.Server.Songs.Song.Stats#SongStats", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<float>("BPM")
                                .HasColumnType("real")
                                .HasColumnName("Stats_BPM");

                            b1.Property<float>("DurationSec")
                                .HasColumnType("real")
                                .HasColumnName("Stats_DurationSec");

                            b1.Property<bool>("IsAutoMapped")
                                .HasColumnType("boolean")
                                .HasColumnName("Stats_IsAutoMapped");
                        });

                    b.HasKey("Id");

                    b.HasAlternateKey("Hash");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.Songs.SongDifficulties.GameModes.GameMode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("GameModes");
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.Songs.SongDifficulties.SongDifficulty", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BLLeaderboardId")
                        .HasColumnType("text");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<int>("GameModeId")
                        .HasColumnType("integer");

                    b.Property<int?>("SSLeaderboardId")
                        .HasColumnType("integer");

                    b.Property<int>("SongId")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Stats", "GuildSaber.Database.Models.Server.Songs.SongDifficulties.SongDifficulty.Stats#SongDifficultyStats", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("BombCount")
                                .HasColumnType("integer")
                                .HasColumnName("Stats_BombCount");

                            b1.Property<double>("Duration")
                                .HasColumnType("double precision")
                                .HasColumnName("Stats_Duration");

                            b1.Property<int>("MaxScore")
                                .HasColumnType("integer");

                            b1.Property<int>("NoteCount")
                                .HasColumnType("integer")
                                .HasColumnName("Stats_NoteCount");

                            b1.Property<float>("NoteJumpSpeed")
                                .HasColumnType("real");

                            b1.Property<float>("NotesPerSecond")
                                .HasColumnType("real")
                                .HasColumnName("Stats_NotesPerSecond");

                            b1.Property<int>("ObstacleCount")
                                .HasColumnType("integer")
                                .HasColumnName("Stats_ObstacleCount");
                        });

                    b.HasKey("Id");

                    b.HasIndex("GameModeId");

                    b.HasIndex("SongId", "GameModeId", "Difficulty")
                        .IsUnique();

                    b.ToTable("SongDifficulties");
                });

            modelBuilder.Entity("RankedMapRankedMapListLevel", b =>
                {
                    b.Property<int>("LevelsId")
                        .HasColumnType("integer");

                    b.Property<long>("RankedMapsId")
                        .HasColumnType("bigint");

                    b.HasKey("LevelsId", "RankedMapsId");

                    b.HasIndex("RankedMapsId");

                    b.ToTable("RankedMapRankedMapListLevel");
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.Guilds.Levels.AccStarLevel", b =>
                {
                    b.HasBaseType("GuildSaber.Database.Models.Server.Guilds.Levels.Level");

                    b.Property<float>("MinStar")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("real")
                        .HasColumnName("MinStar");

                    b.Property<long>("RequiredPassCount")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("RequiredPassCount");

                    b.HasDiscriminator().HasValue((byte)2);
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.Guilds.Levels.DiffStarLevel", b =>
                {
                    b.HasBaseType("GuildSaber.Database.Models.Server.Guilds.Levels.Level");

                    b.Property<float>("MinStar")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("real")
                        .HasColumnName("MinStar");

                    b.Property<long>("RequiredPassCount")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("RequiredPassCount");

                    b.HasDiscriminator().HasValue((byte)1);
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.Guilds.Levels.RankedMapListLevel", b =>
                {
                    b.HasBaseType("GuildSaber.Database.Models.Server.Guilds.Levels.Level");

                    b.Property<long>("RequiredPassCount")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bigint")
                        .HasColumnName("RequiredPassCount");

                    b.HasDiscriminator().HasValue((byte)0);
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.Scores.BeatLeaderScore", b =>
                {
                    b.HasBaseType("GuildSaber.Database.Models.Server.Scores.AbstractScore");

                    b.Property<int?>("BeatLeaderScoreId")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Statistics", "GuildSaber.Database.Models.Server.Scores.BeatLeaderScore.Statistics#ScoreStatistics", b1 =>
                        {
                            b1.Property<string>("Discriminator")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "AccuracyTracker", "GuildSaber.Database.Models.Server.Scores.BeatLeaderScore.Statistics#ScoreStatistics.AccuracyTracker#AccuracyTracker", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<float>("AccLeft")
                                        .HasColumnType("real")
                                        .HasColumnName("AccuracyTracker_AccLeft");

                                    b2.Property<float>("AccRight")
                                        .HasColumnType("real")
                                        .HasColumnName("AccuracyTracker_AccRight");

                                    b2.PrimitiveCollection<float[]>("AccuracyGrid")
                                        .IsRequired()
                                        .HasColumnType("real[]")
                                        .HasColumnName("AccuracyTracker_AccuracyGrid");

                                    b2.PrimitiveCollection<float[]>("LeftAverageCutGraphGrid")
                                        .IsRequired()
                                        .HasColumnType("real[]")
                                        .HasColumnName("AccuracyTracker_LeftAverageCutGraphGrid");

                                    b2.Property<float>("LeftPostSwing")
                                        .HasColumnType("real")
                                        .HasColumnName("AccuracyTracker_LeftPostSwing");

                                    b2.Property<float>("LeftPreSwing")
                                        .HasColumnType("real")
                                        .HasColumnName("AccuracyTracker_LeftPreSwing");

                                    b2.Property<float>("LeftTimeDependence")
                                        .HasColumnType("real")
                                        .HasColumnName("AccuracyTracker_LeftTimeDependence");

                                    b2.PrimitiveCollection<float[]>("RightAverageCutGraphGrid")
                                        .IsRequired()
                                        .HasColumnType("real[]")
                                        .HasColumnName("AccuracyTracker_RightAverageCutGraphGrid");

                                    b2.Property<float>("RightPostSwing")
                                        .HasColumnType("real")
                                        .HasColumnName("AccuracyTracker_RightPostSwing");

                                    b2.Property<float>("RightPreSwing")
                                        .HasColumnType("real")
                                        .HasColumnName("AccuracyTracker_RightPreSwing");

                                    b2.Property<float>("RightTimeDependence")
                                        .HasColumnType("real")
                                        .HasColumnName("AccuracyTracker_RightTimeDependence");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "HitTracker", "GuildSaber.Database.Models.Server.Scores.BeatLeaderScore.Statistics#ScoreStatistics.HitTracker#HitTracker", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<int>("LeftBadCuts")
                                        .HasColumnType("integer")
                                        .HasColumnName("HitTracker_LeftBadCuts");

                                    b2.Property<int>("LeftBombs")
                                        .HasColumnType("integer")
                                        .HasColumnName("HitTracker_LeftBombs");

                                    b2.Property<int>("LeftMiss")
                                        .HasColumnType("integer")
                                        .HasColumnName("HitTracker_LeftMiss");

                                    b2.Property<float>("LeftTiming")
                                        .HasColumnType("real")
                                        .HasColumnName("HitTracker_LeftTiming");

                                    b2.Property<int>("Max115Streak")
                                        .HasColumnType("integer")
                                        .HasColumnName("HitTracker_Max115Streak");

                                    b2.Property<int>("RightBadCuts")
                                        .HasColumnType("integer")
                                        .HasColumnName("HitTracker_RightBadCuts");

                                    b2.Property<int>("RightBombs")
                                        .HasColumnType("integer")
                                        .HasColumnName("HitTracker_RightBombs");

                                    b2.Property<int>("RightMiss")
                                        .HasColumnType("integer")
                                        .HasColumnName("HitTracker_RightMiss");

                                    b2.Property<float>("RightTiming")
                                        .HasColumnType("real")
                                        .HasColumnName("HitTracker_RightTiming");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "ScoreGraphTracker", "GuildSaber.Database.Models.Server.Scores.BeatLeaderScore.Statistics#ScoreStatistics.ScoreGraphTracker#ScoreGraphTracker", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.PrimitiveCollection<List<float>>("Graph")
                                        .IsRequired()
                                        .HasColumnType("real[]")
                                        .HasColumnName("ScoreGraphTracker_Graph");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "WinTracker", "GuildSaber.Database.Models.Server.Scores.BeatLeaderScore.Statistics#ScoreStatistics.WinTracker#WinTracker", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<float>("AverageHeight")
                                        .HasColumnType("real")
                                        .HasColumnName("WinTracker_AverageHeight");

                                    b2.Property<float>("EndTime")
                                        .HasColumnType("real")
                                        .HasColumnName("WinTracker_EndTime");

                                    b2.Property<bool>("IsWin")
                                        .HasColumnType("boolean")
                                        .HasColumnName("WinTracker_IsWin");

                                    b2.Property<float>("JumpDistance")
                                        .HasColumnType("real")
                                        .HasColumnName("WinTracker_JumpDistance");

                                    b2.Property<int>("MaxScore")
                                        .HasColumnType("integer")
                                        .HasColumnName("WinTracker_MaxScore");

                                    b2.Property<int>("PauseCount")
                                        .HasColumnType("integer")
                                        .HasColumnName("WinTracker_PauseCount");

                                    b2.Property<float>("TotalPauseDuration")
                                        .HasColumnType("real")
                                        .HasColumnName("WinTracker_TotalPauseDuration");

                                    b2.Property<int>("TotalScore")
                                        .HasColumnType("integer")
                                        .HasColumnName("WinTracker_TotalScore");

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "AverageHeadPosition", "GuildSaber.Database.Models.Server.Scores.BeatLeaderScore.Statistics#ScoreStatistics.WinTracker#WinTracker.AverageHeadPosition#AverageHeadPosition", b3 =>
                                        {
                                            b3.Property<float>("X")
                                                .HasColumnType("real")
                                                .HasColumnName("AverageHeadPosition_X");

                                            b3.Property<float>("Y")
                                                .HasColumnType("real")
                                                .HasColumnName("AverageHeadPosition_Y");

                                            b3.Property<float>("Z")
                                                .HasColumnType("real")
                                                .HasColumnName("AverageHeadPosition_Z");
                                        });
                                });

                            b1.HasDiscriminator().HasValue("ScoreStatistics");
                        });

                    b.HasDiscriminator().HasValue((byte)1);
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.Scores.ScoreSaberScore", b =>
                {
                    b.HasBaseType("GuildSaber.Database.Models.Server.Scores.AbstractScore");

                    b.Property<string>("DeviceControllerLeft")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DeviceControllerRight")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DeviceHmd")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("ScoreSaberScoreId")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue((byte)0);
                });

            modelBuilder.Entity("CategoryRankedMap", b =>
                {
                    b.HasOne("GuildSaber.Database.Models.Server.Guilds.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuildSaber.Database.Models.Server.RankedMaps.RankedMap", null)
                        .WithMany()
                        .HasForeignKey("RankedMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContextPoint", b =>
                {
                    b.HasOne("GuildSaber.Database.Models.Server.Guilds.Context", null)
                        .WithMany()
                        .HasForeignKey("ContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuildSaber.Database.Models.Server.Guilds.Points.Point", null)
                        .WithMany()
                        .HasForeignKey("PointsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.Auth.Session", b =>
                {
                    b.HasOne("GuildSaber.Database.Models.Server.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.Guilds.Boosts.Boost", b =>
                {
                    b.HasOne("GuildSaber.Database.Models.Server.Guilds.Guild", "Guild")
                        .WithMany("Boosts")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuildSaber.Database.Models.Server.Players.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.Guilds.Categories.Category", b =>
                {
                    b.HasOne("GuildSaber.Database.Models.Server.Guilds.Guild", null)
                        .WithMany("Categories")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.Guilds.Context", b =>
                {
                    b.HasOne("GuildSaber.Database.Models.Server.Guilds.Guild", null)
                        .WithMany("Contexts")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.Guilds.ContextMember", b =>
                {
                    b.HasOne("GuildSaber.Database.Models.Server.Guilds.Context", null)
                        .WithMany("ContextMembers")
                        .HasForeignKey("ContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuildSaber.Database.Models.Server.Guilds.Guild", null)
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuildSaber.Database.Models.Server.Guilds.Members.Member", null)
                        .WithMany("ContextMembers")
                        .HasForeignKey("GuildId", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.Guilds.Levels.Level", b =>
                {
                    b.HasOne("GuildSaber.Database.Models.Server.Guilds.Categories.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GuildSaber.Database.Models.Server.Guilds.Context", "Context")
                        .WithMany("Levels")
                        .HasForeignKey("ContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuildSaber.Database.Models.Server.Guilds.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Context");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.Guilds.Members.Member", b =>
                {
                    b.HasOne("GuildSaber.Database.Models.Server.Guilds.Guild", "Guild")
                        .WithMany("Members")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuildSaber.Database.Models.Server.Players.Player", "Player")
                        .WithMany("Members")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.Guilds.Members.MemberLevelStat", b =>
                {
                    b.HasOne("GuildSaber.Database.Models.Server.Guilds.Levels.Level", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuildSaber.Database.Models.Server.Guilds.ContextMember", null)
                        .WithMany("LevelStats")
                        .HasForeignKey("GuildId", "ContextId", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.Guilds.Members.MemberPointStat", b =>
                {
                    b.HasOne("GuildSaber.Database.Models.Server.Guilds.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GuildSaber.Database.Models.Server.Guilds.Points.Point", "Point")
                        .WithMany()
                        .HasForeignKey("PointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuildSaber.Database.Models.Server.Guilds.ContextMember", null)
                        .WithMany("PointStats")
                        .HasForeignKey("GuildId", "ContextId", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Point");
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.Guilds.Points.Point", b =>
                {
                    b.HasOne("GuildSaber.Database.Models.Server.Guilds.Guild", null)
                        .WithMany("Points")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.RankedMaps.MapVersions.MapVersion", b =>
                {
                    b.HasOne("GuildSaber.Database.Models.Server.RankedMaps.MapVersions.PlayModes.PlayMode", null)
                        .WithMany()
                        .HasForeignKey("PlayModeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuildSaber.Database.Models.Server.RankedMaps.RankedMap", null)
                        .WithMany("MapVersions")
                        .HasForeignKey("RankedMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuildSaber.Database.Models.Server.Songs.SongDifficulties.SongDifficulty", "SongDifficulty")
                        .WithMany()
                        .HasForeignKey("SongDifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuildSaber.Database.Models.Server.Songs.Song", "Song")
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");

                    b.Navigation("SongDifficulty");
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.RankedMaps.RankedMap", b =>
                {
                    b.HasOne("GuildSaber.Database.Models.Server.Guilds.Context", null)
                        .WithMany("RankedMaps")
                        .HasForeignKey("ContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuildSaber.Database.Models.Server.Guilds.Guild", null)
                        .WithMany("RankedMaps")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.RankedScores.RankedScore", b =>
                {
                    b.HasOne("GuildSaber.Database.Models.Server.Guilds.Context", null)
                        .WithMany()
                        .HasForeignKey("ContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuildSaber.Database.Models.Server.Guilds.Guild", null)
                        .WithMany("RankedScores")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuildSaber.Database.Models.Server.Players.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuildSaber.Database.Models.Server.Guilds.Points.Point", null)
                        .WithMany()
                        .HasForeignKey("PointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuildSaber.Database.Models.Server.Scores.AbstractScore", "PrevScore")
                        .WithMany()
                        .HasForeignKey("PrevScoreId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GuildSaber.Database.Models.Server.RankedMaps.RankedMap", "RankedMap")
                        .WithMany()
                        .HasForeignKey("RankedMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuildSaber.Database.Models.Server.Scores.AbstractScore", "Score")
                        .WithMany()
                        .HasForeignKey("ScoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuildSaber.Database.Models.Server.Songs.SongDifficulties.SongDifficulty", "SongDifficulty")
                        .WithMany()
                        .HasForeignKey("SongDifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("PrevScore");

                    b.Navigation("RankedMap");

                    b.Navigation("Score");

                    b.Navigation("SongDifficulty");
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.Scores.AbstractScore", b =>
                {
                    b.HasOne("GuildSaber.Database.Models.Server.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuildSaber.Database.Models.Server.Songs.SongDifficulties.SongDifficulty", null)
                        .WithMany()
                        .HasForeignKey("SongDifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.Songs.SongDifficulties.SongDifficulty", b =>
                {
                    b.HasOne("GuildSaber.Database.Models.Server.Songs.SongDifficulties.GameModes.GameMode", "GameMode")
                        .WithMany()
                        .HasForeignKey("GameModeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuildSaber.Database.Models.Server.Songs.Song", null)
                        .WithMany("SongDifficulties")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameMode");
                });

            modelBuilder.Entity("RankedMapRankedMapListLevel", b =>
                {
                    b.HasOne("GuildSaber.Database.Models.Server.Guilds.Levels.RankedMapListLevel", null)
                        .WithMany()
                        .HasForeignKey("LevelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuildSaber.Database.Models.Server.RankedMaps.RankedMap", null)
                        .WithMany()
                        .HasForeignKey("RankedMapsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.Guilds.Context", b =>
                {
                    b.Navigation("ContextMembers");

                    b.Navigation("Levels");

                    b.Navigation("RankedMaps");
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.Guilds.ContextMember", b =>
                {
                    b.Navigation("LevelStats");

                    b.Navigation("PointStats");
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.Guilds.Guild", b =>
                {
                    b.Navigation("Boosts");

                    b.Navigation("Categories");

                    b.Navigation("Contexts");

                    b.Navigation("Members");

                    b.Navigation("Points");

                    b.Navigation("RankedMaps");

                    b.Navigation("RankedScores");
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.Guilds.Members.Member", b =>
                {
                    b.Navigation("ContextMembers");
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.Players.Player", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.RankedMaps.RankedMap", b =>
                {
                    b.Navigation("MapVersions");
                });

            modelBuilder.Entity("GuildSaber.Database.Models.Server.Songs.Song", b =>
                {
                    b.Navigation("SongDifficulties");
                });
#pragma warning restore 612, 618
        }
    }
}
