// <auto-generated />
using System;
using GuildSaber.Database.Contexts.DiscordBot;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GuildSaber.Database.Contexts.DiscordBot.Migrations
{
    [DbContext(typeof(DiscordBotDbContext))]
    partial class DiscordBotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GuildSaber.Database.Models.DiscordBot.FlexHistories.FlexHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ContextId")
                        .HasColumnType("integer");

                    b.Property<int?>("GlobalLevelId")
                        .HasColumnType("integer");

                    b.Property<int>("GuildId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "ContextId", "Timestamp");

                    b.HasIndex("PlayerId", "GuildId", "ContextId", "Timestamp");

                    b.ToTable("FlexHistories");
                });

            modelBuilder.Entity("GuildSaber.Database.Models.DiscordBot.FlexHistories.FlexHistoryLevelStat", b =>
                {
                    b.Property<long>("FlexHistoryId")
                        .HasColumnType("bigint");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int?>("LevelId")
                        .HasColumnType("integer");

                    b.HasKey("FlexHistoryId", "CategoryId");

                    b.ToTable("FlexHistoryLevelStats");
                });

            modelBuilder.Entity("GuildSaber.Database.Models.DiscordBot.FlexHistories.FlexHistoryPointStat", b =>
                {
                    b.Property<long>("FlexHistoryId")
                        .HasColumnType("bigint");

                    b.Property<int>("PointId")
                        .HasColumnType("integer");

                    b.Property<float>("Points")
                        .HasColumnType("real");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.HasKey("FlexHistoryId", "PointId");

                    b.HasIndex("FlexHistoryId", "PointId")
                        .IsUnique();

                    b.ToTable("FlexHistoryPointStats");
                });

            modelBuilder.Entity("GuildSaber.Database.Models.DiscordBot.FlexHistories.FlexHistoryLevelStat", b =>
                {
                    b.HasOne("GuildSaber.Database.Models.DiscordBot.FlexHistories.FlexHistory", null)
                        .WithMany("LevelStats")
                        .HasForeignKey("FlexHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GuildSaber.Database.Models.DiscordBot.FlexHistories.FlexHistoryPointStat", b =>
                {
                    b.HasOne("GuildSaber.Database.Models.DiscordBot.FlexHistories.FlexHistory", null)
                        .WithMany("PointStats")
                        .HasForeignKey("FlexHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GuildSaber.Database.Models.DiscordBot.FlexHistories.FlexHistory", b =>
                {
                    b.Navigation("LevelStats");

                    b.Navigation("PointStats");
                });
#pragma warning restore 612, 618
        }
    }
}
