using GuildSaber.Common.Services.BeatLeader.Models;
using GuildSaber.Database.Models.Server.Players;

namespace GuildSaber.Database.Models.Mappers.BeatLeader;

public static class HMDMapper
{
    public static HMD Map(this PlayerHardwareInfo.EHMD self)
        => self switch
        {
            PlayerHardwareInfo.EHMD.Unknown => HMD.Unknown,
            PlayerHardwareInfo.EHMD.Rift => HMD.Rift,
            PlayerHardwareInfo.EHMD.Vive => HMD.Vive,
            PlayerHardwareInfo.EHMD.VivePro => HMD.VivePro,
            PlayerHardwareInfo.EHMD.WMR => HMD.WMR,
            PlayerHardwareInfo.EHMD.RiftS => HMD.RiftS,
            PlayerHardwareInfo.EHMD.Quest => HMD.Quest,
            PlayerHardwareInfo.EHMD.Index => HMD.Index,
            PlayerHardwareInfo.EHMD.ViveCosmos => HMD.ViveCosmos,
            PlayerHardwareInfo.EHMD.Quest2 => HMD.Quest2,
            PlayerHardwareInfo.EHMD.Quest3 => HMD.Quest3,
            PlayerHardwareInfo.EHMD.Quest3S => HMD.Quest3S,
            PlayerHardwareInfo.EHMD.PicoNeo3 => HMD.PicoNeo3,
            PlayerHardwareInfo.EHMD.PicoNeo2 => HMD.PicoNeo2,
            PlayerHardwareInfo.EHMD.VivePro2 => HMD.VivePro2,
            PlayerHardwareInfo.EHMD.ViveElite => HMD.ViveElite,
            PlayerHardwareInfo.EHMD.Miramar => HMD.Miramar,
            PlayerHardwareInfo.EHMD.Pimax8K => HMD.Pimax8K,
            PlayerHardwareInfo.EHMD.Pimax5K => HMD.Pimax5K,
            PlayerHardwareInfo.EHMD.PimaxArtisan => HMD.PimaxArtisan,
            PlayerHardwareInfo.EHMD.HpReverb => HMD.HpReverb,
            PlayerHardwareInfo.EHMD.SamsungWMR => HMD.SamsungWMR,
            PlayerHardwareInfo.EHMD.QiyuDream => HMD.QiyuDream,
            PlayerHardwareInfo.EHMD.Disco => HMD.Disco,
            PlayerHardwareInfo.EHMD.LenovoExplorer => HMD.LenovoExplorer,
            PlayerHardwareInfo.EHMD.AcerWMR => HMD.AcerWMR,
            PlayerHardwareInfo.EHMD.ViveFocus => HMD.ViveFocus,
            PlayerHardwareInfo.EHMD.Arpara => HMD.Arpara,
            PlayerHardwareInfo.EHMD.DellVisor => HMD.DellVisor,
            PlayerHardwareInfo.EHMD.E3 => HMD.E3,
            PlayerHardwareInfo.EHMD.ViveDvt => HMD.ViveDvt,
            PlayerHardwareInfo.EHMD.Glasses20 => HMD.Glasses20,
            PlayerHardwareInfo.EHMD.Hedy => HMD.Hedy,
            PlayerHardwareInfo.EHMD.Vaporeon => HMD.Vaporeon,
            PlayerHardwareInfo.EHMD.Huaweivr => HMD.Huaweivr,
            PlayerHardwareInfo.EHMD.AsusWMR => HMD.AsusWMR,
            PlayerHardwareInfo.EHMD.CloudXR => HMD.CloudXR,
            PlayerHardwareInfo.EHMD.Vridge => HMD.Vridge,
            PlayerHardwareInfo.EHMD.Medion => HMD.Medion,
            PlayerHardwareInfo.EHMD.PicoNeo4 => HMD.PicoNeo4,
            PlayerHardwareInfo.EHMD.QuestPro => HMD.QuestPro,
            PlayerHardwareInfo.EHMD.PimaxCrystal => HMD.PimaxCrystal,
            PlayerHardwareInfo.EHMD.E4 => HMD.E4,
            PlayerHardwareInfo.EHMD.Controllable => HMD.Controllable,
            PlayerHardwareInfo.EHMD.BigScreenBeyond => HMD.BigScreenBeyond,
            PlayerHardwareInfo.EHMD.Nolosonic => HMD.Nolosonic,
            PlayerHardwareInfo.EHMD.Hypereal => HMD.Hypereal,
            PlayerHardwareInfo.EHMD.Varjoaero => HMD.Varjoaero,
            PlayerHardwareInfo.EHMD.PSVR2 => HMD.PSVR2,
            PlayerHardwareInfo.EHMD.Megane1 => HMD.Megane1,
            PlayerHardwareInfo.EHMD.VarjoXR3 => HMD.VarjoXR3,
            _ => HMD.Unknown
        };

    public static PlayerHardwareInfo.EHMD Map(this HMD self)
        => self switch
        {
            HMD.Unknown => PlayerHardwareInfo.EHMD.Unknown,
            HMD.Rift => PlayerHardwareInfo.EHMD.Rift,
            HMD.Vive => PlayerHardwareInfo.EHMD.Vive,
            HMD.VivePro => PlayerHardwareInfo.EHMD.VivePro,
            HMD.WMR => PlayerHardwareInfo.EHMD.WMR,
            HMD.RiftS => PlayerHardwareInfo.EHMD.RiftS,
            HMD.Quest => PlayerHardwareInfo.EHMD.Quest,
            HMD.Index => PlayerHardwareInfo.EHMD.Index,
            HMD.ViveCosmos => PlayerHardwareInfo.EHMD.ViveCosmos,
            HMD.Quest2 => PlayerHardwareInfo.EHMD.Quest2,
            HMD.Quest3 => PlayerHardwareInfo.EHMD.Quest3,
            HMD.Quest3S => PlayerHardwareInfo.EHMD.Quest3S,
            HMD.PicoNeo3 => PlayerHardwareInfo.EHMD.PicoNeo3,
            HMD.PicoNeo2 => PlayerHardwareInfo.EHMD.PicoNeo2,
            HMD.VivePro2 => PlayerHardwareInfo.EHMD.VivePro2,
            HMD.ViveElite => PlayerHardwareInfo.EHMD.ViveElite,
            HMD.Miramar => PlayerHardwareInfo.EHMD.Miramar,
            HMD.Pimax8K => PlayerHardwareInfo.EHMD.Pimax8K,
            HMD.Pimax5K => PlayerHardwareInfo.EHMD.Pimax5K,
            HMD.PimaxArtisan => PlayerHardwareInfo.EHMD.PimaxArtisan,
            HMD.HpReverb => PlayerHardwareInfo.EHMD.HpReverb,
            HMD.SamsungWMR => PlayerHardwareInfo.EHMD.SamsungWMR,
            HMD.QiyuDream => PlayerHardwareInfo.EHMD.QiyuDream,
            HMD.Disco => PlayerHardwareInfo.EHMD.Disco,
            HMD.LenovoExplorer => PlayerHardwareInfo.EHMD.LenovoExplorer,
            HMD.AcerWMR => PlayerHardwareInfo.EHMD.AcerWMR,
            HMD.ViveFocus => PlayerHardwareInfo.EHMD.ViveFocus,
            HMD.Arpara => PlayerHardwareInfo.EHMD.Arpara,
            HMD.DellVisor => PlayerHardwareInfo.EHMD.DellVisor,
            HMD.E3 => PlayerHardwareInfo.EHMD.E3,
            HMD.ViveDvt => PlayerHardwareInfo.EHMD.ViveDvt,
            HMD.Glasses20 => PlayerHardwareInfo.EHMD.Glasses20,
            HMD.Hedy => PlayerHardwareInfo.EHMD.Hedy,
            HMD.Vaporeon => PlayerHardwareInfo.EHMD.Vaporeon,
            HMD.Huaweivr => PlayerHardwareInfo.EHMD.Huaweivr,
            HMD.AsusWMR => PlayerHardwareInfo.EHMD.AsusWMR,
            HMD.CloudXR => PlayerHardwareInfo.EHMD.CloudXR,
            HMD.Vridge => PlayerHardwareInfo.EHMD.Vridge,
            HMD.Medion => PlayerHardwareInfo.EHMD.Medion,
            HMD.PicoNeo4 => PlayerHardwareInfo.EHMD.PicoNeo4,
            HMD.QuestPro => PlayerHardwareInfo.EHMD.QuestPro,
            HMD.PimaxCrystal => PlayerHardwareInfo.EHMD.PimaxCrystal,
            HMD.E4 => PlayerHardwareInfo.EHMD.E4,
            HMD.Controllable => PlayerHardwareInfo.EHMD.Controllable,
            HMD.BigScreenBeyond => PlayerHardwareInfo.EHMD.BigScreenBeyond,
            HMD.Nolosonic => PlayerHardwareInfo.EHMD.Nolosonic,
            HMD.Hypereal => PlayerHardwareInfo.EHMD.Hypereal,
            HMD.Varjoaero => PlayerHardwareInfo.EHMD.Varjoaero,
            HMD.PSVR2 => PlayerHardwareInfo.EHMD.PSVR2,
            HMD.Megane1 => PlayerHardwareInfo.EHMD.Megane1,
            HMD.VarjoXR3 => PlayerHardwareInfo.EHMD.VarjoXR3,
            _ => PlayerHardwareInfo.EHMD.Unknown
        };
}