// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client"
import { client } from "./client.gen"
import type {
  BeatLeaderCallbackData,
  BeatLeaderCallbackErrors,
  BeatLeaderCallbackResponses,
  BeatLeaderCallbackWithRedirectData,
  BeatLeaderCallbackWithRedirectErrors,
  BeatLeaderCallbackWithRedirectResponses,
  BeatLeaderLoginData,
  BeatLeaderLoginResponses,
  CreateCategoryData,
  CreateCategoryErrors,
  CreateCategoryResponses,
  CreateGuildData,
  CreateGuildErrors,
  CreateGuildResponses,
  CreateRankedMapData,
  CreateRankedMapErrors,
  CreateRankedMapResponses,
  DeleteCategoryData,
  DeleteCategoryErrors,
  DeleteCategoryResponses,
  DeleteGuildData,
  DeleteGuildErrors,
  DeleteGuildResponses,
  DeletePlayerData,
  DeletePlayerErrors,
  DeletePlayerResponses,
  DiscordCallbackData,
  DiscordCallbackErrors,
  DiscordCallbackResponses,
  DiscordCallbackWithRedirectData,
  DiscordCallbackWithRedirectErrors,
  DiscordCallbackWithRedirectResponses,
  DiscordLinkCallbackData,
  DiscordLinkCallbackErrors,
  DiscordLinkCallbackResponses,
  DiscordLinkCallbackWithRedirectData,
  DiscordLinkCallbackWithRedirectErrors,
  DiscordLinkCallbackWithRedirectResponses,
  DiscordLinkData,
  DiscordLinkResponses,
  DiscordLoginData,
  DiscordLoginResponses,
  GetCategoriesData,
  GetCategoriesPaginatedData,
  GetCategoriesPaginatedResponses,
  GetCategoriesResponses,
  GetCategoryData,
  GetCategoryErrors,
  GetCategoryResponses,
  GetContextPointRankedMapLeaderboardData,
  GetContextPointRankedMapLeaderboardResponses,
  GetCurrentMemberContextStatsData,
  GetCurrentMemberContextStatsErrors,
  GetCurrentMemberContextStatsResponses,
  GetCurrentMemberLevelStatsData,
  GetCurrentMemberLevelStatsResponses,
  GetGuildByDiscordIdData,
  GetGuildByDiscordIdErrors,
  GetGuildByDiscordIdResponses,
  GetGuildData,
  GetGuildErrors,
  GetGuildExtendedData,
  GetGuildExtendedErrors,
  GetGuildExtendedResponses,
  GetGuildResponses,
  GetGuildsData,
  GetGuildsResponses,
  GetGuildStatsData,
  GetGuildStatsErrors,
  GetGuildStatsResponses,
  GetLevelPlaylistData,
  GetLevelPlaylistErrors,
  GetLevelPlaylistResponses,
  GetLevelsData,
  GetLevelsResponses,
  GetMemberCategoryPointStatLeaderboardData,
  GetMemberCategoryPointStatLeaderboardResponses,
  GetMemberContextStatsData,
  GetMemberContextStatsErrors,
  GetMemberContextStatsResponses,
  GetMemberData,
  GetMemberErrors,
  GetMemberLevelStatsData,
  GetMemberLevelStatsResponses,
  GetMemberPointStatLeaderboardData,
  GetMemberPointStatLeaderboardResponses,
  GetMemberResponses,
  GetMembersData,
  GetMembersResponses,
  GetPlayerAtMeData,
  GetPlayerAtMeErrors,
  GetPlayerAtMeResponses,
  GetPlayerData,
  GetPlayerErrors,
  GetPlayerExtendedAtMeData,
  GetPlayerExtendedAtMeErrors,
  GetPlayerExtendedAtMeResponses,
  GetPlayerExtendedData,
  GetPlayerExtendedErrors,
  GetPlayerExtendedResponses,
  GetPlayerRankedScoresAtMeData,
  GetPlayerRankedScoresAtMeResponses,
  GetPlayerRankedScoresData,
  GetPlayerRankedScoresResponses,
  GetPlayerRankedScoresWithRankedMapAtMeData,
  GetPlayerRankedScoresWithRankedMapAtMeResponses,
  GetPlayerRankedScoresWithRankedMapData,
  GetPlayerRankedScoresWithRankedMapResponses,
  GetPlayerResponses,
  GetPlayersData,
  GetPlayersResponses,
  GetRankedMapData,
  GetRankedMapErrors,
  GetRankedMapResponses,
  GetRankedMapsData,
  GetRankedMapsResponses,
  ImportOldGuildSaberMapsBackgroundData,
  ImportOldGuildSaberMapsBackgroundErrors,
  ImportOldGuildSaberMapsBackgroundResponses,
  JoinGuildAtMeData,
  JoinGuildAtMeErrors,
  JoinGuildAtMeResponses,
  JoinGuildData,
  JoinGuildErrors,
  JoinGuildResponses,
  LogoutData,
  LogoutResponses,
  LookupGuildByDiscordGuildIdData,
  LookupGuildByDiscordGuildIdErrors,
  LookupGuildByDiscordGuildIdResponses,
  LookupPlayerByDiscordIdData,
  LookupPlayerByDiscordIdErrors,
  LookupPlayerByDiscordIdResponses,
  PatchGuildData,
  PatchGuildErrors,
  PatchGuildResponses,
  PostDebugDeleteMemberPointStatsByPlayerIdData,
  PostDebugDeleteMemberPointStatsByPlayerIdResponses,
  PostDebugImportBeatleaderScoresByPlayerIdData,
  PostDebugImportBeatleaderScoresByPlayerIdErrors,
  PostDebugImportBeatleaderScoresByPlayerIdResponses,
  PostDebugImportScoresaberScoresByPlayerIdData,
  PostDebugImportScoresaberScoresByPlayerIdErrors,
  PostDebugImportScoresaberScoresByPlayerIdResponses,
  PostDebugRecalculateMemberLevelsByPlayerIdData,
  PostDebugRecalculateMemberLevelsByPlayerIdResponses,
  PostDebugRecalculateMemberPointsByPlayerIdData,
  PostDebugRecalculateMemberPointsByPlayerIdResponses,
  PostDebugRecalculatePlayerScoresByPlayerIdData,
  PostDebugRecalculatePlayerScoresByPlayerIdResponses,
  PostDebugRemoveAllRankedMapsData,
  PostDebugRemoveAllRankedMapsResponses,
  PostDebugRemoveAllRankedScoresData,
  PostDebugRemoveAllRankedScoresResponses,
  PostDebugRemoveAllScoresData,
  PostDebugRemoveAllScoresResponses,
  UpdateCategoryData,
  UpdateCategoryResponses,
} from "./types.gen"

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<
  TData,
  ThrowOnError
> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

/**
 * Get the playlist for a ranked map list level.
 *
 * Get the playlist associated with a ranked map list level by its Id.
 */
export const getLevelPlaylist = <ThrowOnError extends boolean = false>(
  options: Options<GetLevelPlaylistData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetLevelPlaylistResponses, GetLevelPlaylistErrors, ThrowOnError>({
    url: "/levels/{levelId}/playlist",
    ...options,
  })

/**
 * Get all ranked scores of a player paginated
 *
 * Get all ranked scores of a specific player by their Id, with optional sorting.
 */
export const getPlayerRankedScores = <ThrowOnError extends boolean = false>(
  options: Options<GetPlayerRankedScoresData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetPlayerRankedScoresResponses, unknown, ThrowOnError>({
    url: "/players/{playerId}/contexts/{contextId}/ranked-scores",
    ...options,
  })

/**
 * Get current player's ranked scores paginated
 *
 * Get the current player's ranked scores using their player id from claims, with optional sorting.
 */
export const getPlayerRankedScoresAtMe = <ThrowOnError extends boolean = false>(
  options: Options<GetPlayerRankedScoresAtMeData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetPlayerRankedScoresAtMeResponses, unknown, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/players/@me/contexts/{contextId}/ranked-scores",
    ...options,
  })

/**
 * Get all ranked scores of a player with ranked map paginated
 *
 * Get all ranked scores of a specific player by their Id along with ranked map, with optional sorting.
 */
export const getPlayerRankedScoresWithRankedMap = <ThrowOnError extends boolean = false>(
  options: Options<GetPlayerRankedScoresWithRankedMapData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetPlayerRankedScoresWithRankedMapResponses, unknown, ThrowOnError>({
    url: "/players/{playerId}/contexts/{contextId}/ranked-scores-with-ranked-map",
    ...options,
  })

/**
 * Get current player's ranked scores with ranked map paginated
 *
 * Get the current player's ranked scores along with ranked map using their player id from claims, with optional sorting.
 */
export const getPlayerRankedScoresWithRankedMapAtMe = <ThrowOnError extends boolean = false>(
  options: Options<GetPlayerRankedScoresWithRankedMapAtMeData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetPlayerRankedScoresWithRankedMapAtMeResponses, unknown, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/players/@me/contexts/{contextId}/ranked-scores-with-ranked-map",
    ...options,
  })

/**
 * Get a ranked map.
 *
 * Get a ranked map in the server by its Id.
 */
export const getRankedMap = <ThrowOnError extends boolean = false>(options: Options<GetRankedMapData, ThrowOnError>) =>
  (options.client ?? client).get<GetRankedMapResponses, GetRankedMapErrors, ThrowOnError>({
    url: "/ranked-maps/{rankedMapId}",
    ...options,
  })

/**
 * Get ranked maps for a context.
 *
 * Get ranked maps for a context by its Id, with optional search and sorting.
 */
export const getRankedMaps = <ThrowOnError extends boolean = false>(
  options: Options<GetRankedMapsData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetRankedMapsResponses, unknown, ThrowOnError>({
    url: "/contexts/{contextId}/ranked-maps",
    ...options,
  })

/**
 * Create a ranked map for a context.
 *
 *     This endpoint:
 * * Returns 200 OK with ranked map details when created successfully.
 * * Returns 401 Unauthorized when the guild has reached its maximum number of ranked maps.
 * * Returns 400 Bad Request with validation details when validation fails.
 * * Returns 404 Not Found when the map is not found on BeatSaver.
 * * Returns 429 Too Many Requests when rate limited by BeatSaver API.
 * * Returns 500 Internal Server Error when BeatSaver API fails.
 */
export const createRankedMap = <ThrowOnError extends boolean = false>(
  options: Options<CreateRankedMapData, ThrowOnError>,
) =>
  (options.client ?? client).post<CreateRankedMapResponses, CreateRankedMapErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/contexts/{contextId}/ranked-maps",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Get all players paginated
 *
 * Get all players in the server, with optional search and sorting.
 */
export const getPlayers = <ThrowOnError extends boolean = false>(options?: Options<GetPlayersData, ThrowOnError>) =>
  (options?.client ?? client).get<GetPlayersResponses, unknown, ThrowOnError>({ url: "/players", ...options })

/**
 * Delete a player
 *
 * Delete a specific player by their Id.
 */
export const deletePlayer = <ThrowOnError extends boolean = false>(options: Options<DeletePlayerData, ThrowOnError>) =>
  (options.client ?? client).delete<DeletePlayerResponses, DeletePlayerErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/players/{playerId}",
    ...options,
  })

/**
 * Get a player
 *
 * Get a specific player by their Id.
 */
export const getPlayer = <ThrowOnError extends boolean = false>(options: Options<GetPlayerData, ThrowOnError>) =>
  (options.client ?? client).get<GetPlayerResponses, GetPlayerErrors, ThrowOnError>({
    url: "/players/{playerId}",
    ...options,
  })

/**
 * Get current player
 *
 * Get the current player information.
 */
export const getPlayerAtMe = <ThrowOnError extends boolean = false>(
  options?: Options<GetPlayerAtMeData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetPlayerAtMeResponses, GetPlayerAtMeErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/players/@me",
    ...options,
  })

/**
 * Get a player with extended information
 *
 * Get a specific player with extended information by their Id. Which includes additional fields like guilds and permissions.
 */
export const getPlayerExtended = <ThrowOnError extends boolean = false>(
  options: Options<GetPlayerExtendedData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetPlayerExtendedResponses, GetPlayerExtendedErrors, ThrowOnError>({
    url: "/players/{playerId}/extended",
    ...options,
  })

/**
 * Get current player with extended information
 *
 * Get the current player information alongside their guilds and permissions.
 */
export const getPlayerExtendedAtMe = <ThrowOnError extends boolean = false>(
  options?: Options<GetPlayerExtendedAtMeData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetPlayerExtendedAtMeResponses, GetPlayerExtendedAtMeErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/players/@me/extended",
    ...options,
  })

/**
 * Lookup player ID by Discord ID
 *
 * Resolve a player's ID from their linked Discord account ID.
 */
export const lookupPlayerByDiscordId = <ThrowOnError extends boolean = false>(
  options: Options<LookupPlayerByDiscordIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<LookupPlayerByDiscordIdResponses, LookupPlayerByDiscordIdErrors, ThrowOnError>({
    url: "/players/lookup/discord/{discordId}",
    ...options,
  })

/**
 * Get the leaderboard for a ranked map within a context point, paginated.
 *
 * Get the leaderboard for a ranked map within a context point by its Id, paginated.
 */
export const getContextPointRankedMapLeaderboard = <ThrowOnError extends boolean = false>(
  options: Options<GetContextPointRankedMapLeaderboardData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetContextPointRankedMapLeaderboardResponses, unknown, ThrowOnError>({
    url: "/contexts/{contextId}/points/{pointId}/ranked-maps/{rankedMapId}/leaderboard",
    ...options,
  })

/**
 * Get the guild member's leaderboard for a point within a context, paginated.
 *
 * Get the guild member's leaderboard for a point within a context by its Id, paginated.
 */
export const getMemberPointStatLeaderboard = <ThrowOnError extends boolean = false>(
  options: Options<GetMemberPointStatLeaderboardData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetMemberPointStatLeaderboardResponses, unknown, ThrowOnError>({
    url: "/contexts/{contextId}/points/{pointId}/leaderboard",
    ...options,
  })

/**
 * Get the guild member's leaderboard for a category point within a context, paginated.
 *
 * Get the guild member's leaderboard for a category point within a context by its Id, paginated.
 */
export const getMemberCategoryPointStatLeaderboard = <ThrowOnError extends boolean = false>(
  options: Options<GetMemberCategoryPointStatLeaderboardData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetMemberCategoryPointStatLeaderboardResponses, unknown, ThrowOnError>({
    url: "/contexts/{contextId}/points/{pointId}/categories/{categoryId}/leaderboard",
    ...options,
  })

/**
 * Get all guilds paginated
 *
 * Get all guilds in the server, with optional search and sorting.
 */
export const getGuilds = <ThrowOnError extends boolean = false>(options?: Options<GetGuildsData, ThrowOnError>) =>
  (options?.client ?? client).get<GetGuildsResponses, unknown, ThrowOnError>({ url: "/guilds", ...options })

/**
 * Create a guild as the current player
 *
 * Create a guild as the current player using their player id from claims.
 */
export const createGuild = <ThrowOnError extends boolean = false>(options: Options<CreateGuildData, ThrowOnError>) =>
  (options.client ?? client).post<CreateGuildResponses, CreateGuildErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/guilds",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Delete a guild
 *
 * Delete a guild by its Id.
 */
export const deleteGuild = <ThrowOnError extends boolean = false>(options: Options<DeleteGuildData, ThrowOnError>) =>
  (options.client ?? client).delete<DeleteGuildResponses, DeleteGuildErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/guilds/{guildId}",
    ...options,
  })

/**
 * Get a guild
 *
 * Get a specific guild by its Id.
 */
export const getGuild = <ThrowOnError extends boolean = false>(options: Options<GetGuildData, ThrowOnError>) =>
  (options.client ?? client).get<GetGuildResponses, GetGuildErrors, ThrowOnError>({
    url: "/guilds/{guildId}",
    ...options,
  })

/**
 * Patch a guild
 *
 * Edit fields of a guild only by the given properties (json patch rfc6902).
 */
export const patchGuild = <ThrowOnError extends boolean = false>(options: Options<PatchGuildData, ThrowOnError>) =>
  (options.client ?? client).patch<PatchGuildResponses, PatchGuildErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/guilds/{guildId}",
    ...options,
    headers: {
      "Content-Type": "application/json-patch+json",
      ...options.headers,
    },
  })

/**
 * Get a guild with extended information
 *
 * Get a specific guild with extended information by its Id. Which includes additional fields like categories and points.
 */
export const getGuildExtended = <ThrowOnError extends boolean = false>(
  options: Options<GetGuildExtendedData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetGuildExtendedResponses, GetGuildExtendedErrors, ThrowOnError>({
    url: "/guilds/{guildId}/extended",
    ...options,
  })

/**
 * Get a guild by Discord guild ID
 *
 * Get a specific guild by its Discord guild ID.
 */
export const getGuildByDiscordId = <ThrowOnError extends boolean = false>(
  options: Options<GetGuildByDiscordIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetGuildByDiscordIdResponses, GetGuildByDiscordIdErrors, ThrowOnError>({
    url: "/guilds/by-discord-id/{discordGuildId}",
    ...options,
  })

/**
 * Lookup guild ID by Discord guild ID
 *
 * Resolve a guild's ID from its linked Discord guild ID.
 */
export const lookupGuildByDiscordGuildId = <ThrowOnError extends boolean = false>(
  options: Options<LookupGuildByDiscordGuildIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<LookupGuildByDiscordGuildIdResponses, LookupGuildByDiscordGuildIdErrors, ThrowOnError>(
    { url: "/guilds/lookup/discord/{discordGuildId}", ...options },
  )

/**
 * Get all members of a guild.
 *
 * Get all members of a guild by guild id.
 */
export const getMembers = <ThrowOnError extends boolean = false>(options: Options<GetMembersData, ThrowOnError>) =>
  (options.client ?? client).get<GetMembersResponses, unknown, ThrowOnError>({
    url: "/guilds/{guildId}/members",
    ...options,
  })

/**
 * Join a guild as the current player.
 *
 * Join a guild as the current player using their player id from claims.
 */
export const joinGuildAtMe = <ThrowOnError extends boolean = false>(
  options: Options<JoinGuildAtMeData, ThrowOnError>,
) =>
  (options.client ?? client).post<JoinGuildAtMeResponses, JoinGuildAtMeErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/guilds/{guildId}/members",
    ...options,
  })

/**
 * Get a member of a guild
 *
 * Get a member of a guild by player id.
 */
export const getMember = <ThrowOnError extends boolean = false>(options: Options<GetMemberData, ThrowOnError>) =>
  (options.client ?? client).get<GetMemberResponses, GetMemberErrors, ThrowOnError>({
    url: "/guilds/{guildId}/members/{playerId}",
    ...options,
  })

/**
 * Join a guild
 *
 * Join a guild by player id.
 */
export const joinGuild = <ThrowOnError extends boolean = false>(options: Options<JoinGuildData, ThrowOnError>) =>
  (options.client ?? client).post<JoinGuildResponses, JoinGuildErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/guilds/{guildId}/members/{playerId}",
    ...options,
  })

/**
 * Get level stats for a guild member.
 *
 * Get level statistics for a specific player within a context.
 */
export const getMemberLevelStats = <ThrowOnError extends boolean = false>(
  options: Options<GetMemberLevelStatsData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetMemberLevelStatsResponses, unknown, ThrowOnError>({
    url: "/contexts/{contextId}/members/{playerId}/level-stats",
    ...options,
  })

/**
 * Get level stats for the current authenticated member.
 *
 * Get level statistics for the current authenticated player within a context.
 */
export const getCurrentMemberLevelStats = <ThrowOnError extends boolean = false>(
  options: Options<GetCurrentMemberLevelStatsData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetCurrentMemberLevelStatsResponses, unknown, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/contexts/{contextId}/members/@me/level-stats",
    ...options,
  })

/**
 * Get context stats for a guild member.
 *
 * Get context statistics for a specific player within a context.
 */
export const getMemberContextStats = <ThrowOnError extends boolean = false>(
  options: Options<GetMemberContextStatsData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetMemberContextStatsResponses, GetMemberContextStatsErrors, ThrowOnError>({
    url: "/contexts/{contextId}/members/{playerId}/context-stats",
    ...options,
  })

/**
 * Get context stats for the current authenticated member.
 *
 * Get context statistics for the current authenticated player within a context.
 */
export const getCurrentMemberContextStats = <ThrowOnError extends boolean = false>(
  options: Options<GetCurrentMemberContextStatsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetCurrentMemberContextStatsResponses,
    GetCurrentMemberContextStatsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/contexts/{contextId}/members/@me/context-stats",
    ...options,
  })

/**
 * Get all levels in a context, optionally filtered by category.
 *
 * - No parameters: Returns all levels.
 * - hasCategory=false: Returns levels with no category.
 * - category=5: Returns levels in category 5.
 */
export const getLevels = <ThrowOnError extends boolean = false>(options: Options<GetLevelsData, ThrowOnError>) =>
  (options.client ?? client).get<GetLevelsResponses, unknown, ThrowOnError>({
    url: "/context/{contextId}/levels",
    ...options,
  })

/**
 * Get the statistics of the guild by guild id.
 *
 * Get the statistics of the guild by guild id.
 */
export const getGuildStats = <ThrowOnError extends boolean = false>(
  options: Options<GetGuildStatsData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetGuildStatsResponses, GetGuildStatsErrors, ThrowOnError>({
    url: "/guilds/{guildId}/stats",
    ...options,
  })

/**
 * Get all categories paginated.
 *
 * Get all categories in the server.
 */
export const getCategoriesPaginated = <ThrowOnError extends boolean = false>(
  options?: Options<GetCategoriesPaginatedData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetCategoriesPaginatedResponses, unknown, ThrowOnError>({
    url: "/categories",
    ...options,
  })

/**
 * Get a category.
 *
 * Get a category in the server by its Id.
 */
export const getCategory = <ThrowOnError extends boolean = false>(options: Options<GetCategoryData, ThrowOnError>) =>
  (options.client ?? client).get<GetCategoryResponses, GetCategoryErrors, ThrowOnError>({
    url: "/categories/{categoryId}",
    ...options,
  })

/**
 * Get all categories of a guild.
 *
 * Get all categories of a guild by guild id.
 */
export const getCategories = <ThrowOnError extends boolean = false>(
  options: Options<GetCategoriesData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetCategoriesResponses, unknown, ThrowOnError>({
    url: "/guilds/{guildId}/categories",
    ...options,
  })

/**
 * Create a category for a guild.
 *
 * Create a category for a guild by its Id.
 */
export const createCategory = <ThrowOnError extends boolean = false>(
  options: Options<CreateCategoryData, ThrowOnError>,
) =>
  (options.client ?? client).post<CreateCategoryResponses, CreateCategoryErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/guilds/{guildId}/categories",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Delete a category of a guild.
 *
 * Delete a category of a guild by its Id.
 */
export const deleteCategory = <ThrowOnError extends boolean = false>(
  options: Options<DeleteCategoryData, ThrowOnError>,
) =>
  (options.client ?? client).delete<DeleteCategoryResponses, DeleteCategoryErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/guilds/{guildId}/categories/{categoryId}",
    ...options,
  })

/**
 * Update a category of a guild.
 *
 * Update a category of a guild by its Id.
 */
export const updateCategory = <ThrowOnError extends boolean = false>(
  options: Options<UpdateCategoryData, ThrowOnError>,
) =>
  (options.client ?? client).put<UpdateCategoryResponses, unknown, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/guilds/{guildId}/categories/{categoryId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Import ranked maps from old GuildSaber
 *
 * Import ranked maps from old GuildSaber for a specific guild.
 */
export const importOldGuildSaberMapsBackground = <ThrowOnError extends boolean = false>(
  options: Options<ImportOldGuildSaberMapsBackgroundData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ImportOldGuildSaberMapsBackgroundResponses,
    ImportOldGuildSaberMapsBackgroundErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/debug/import-old-gs-maps/{guildId}",
    ...options,
  })

/**
 * Enqueue BeatLeader player scores import.
 *
 * Queues a background task to import all scores for the specified player from BeatLeader.
 */
export const postDebugImportBeatleaderScoresByPlayerId = <ThrowOnError extends boolean = false>(
  options: Options<PostDebugImportBeatleaderScoresByPlayerIdData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostDebugImportBeatleaderScoresByPlayerIdResponses,
    PostDebugImportBeatleaderScoresByPlayerIdErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/debug/import-beatleader-scores/{playerId}",
    ...options,
  })

/**
 * Enqueue ScoreSaber player scores import.
 *
 * Queues a background task to import all scores for the specified player from ScoreSaber.
 */
export const postDebugImportScoresaberScoresByPlayerId = <ThrowOnError extends boolean = false>(
  options: Options<PostDebugImportScoresaberScoresByPlayerIdData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostDebugImportScoresaberScoresByPlayerIdResponses,
    PostDebugImportScoresaberScoresByPlayerIdErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/debug/import-scoresaber-scores/{playerId}",
    ...options,
  })

/**
 * Remove all scores from the database.
 *
 * Deletes all ranked scores from the database. USE WITH CAUTION!
 */
export const postDebugRemoveAllScores = <ThrowOnError extends boolean = false>(
  options?: Options<PostDebugRemoveAllScoresData, ThrowOnError>,
) =>
  (options?.client ?? client).post<PostDebugRemoveAllScoresResponses, unknown, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/debug/remove-all-scores",
    ...options,
  })

/**
 * Remove all ranked scores from the database.
 *
 * Deletes all ranked scores from the database. USE WITH CAUTION!
 */
export const postDebugRemoveAllRankedScores = <ThrowOnError extends boolean = false>(
  options?: Options<PostDebugRemoveAllRankedScoresData, ThrowOnError>,
) =>
  (options?.client ?? client).post<PostDebugRemoveAllRankedScoresResponses, unknown, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/debug/remove-all-ranked-scores",
    ...options,
  })

/**
 * Remove all ranked maps from the database.
 *
 * Deletes all ranked maps from the database. USE WITH CAUTION!
 */
export const postDebugRemoveAllRankedMaps = <ThrowOnError extends boolean = false>(
  options?: Options<PostDebugRemoveAllRankedMapsData, ThrowOnError>,
) =>
  (options?.client ?? client).post<PostDebugRemoveAllRankedMapsResponses, unknown, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/debug/remove-all-ranked-maps",
    ...options,
  })

/**
 * Recalculate member points for a player.
 *
 * Recalculates member points for all contexts the player is a member of.
 */
export const postDebugRecalculateMemberPointsByPlayerId = <ThrowOnError extends boolean = false>(
  options: Options<PostDebugRecalculateMemberPointsByPlayerIdData, ThrowOnError>,
) =>
  (options.client ?? client).post<PostDebugRecalculateMemberPointsByPlayerIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/debug/recalculate-member-points/{playerId}",
    ...options,
  })

/**
 * Recalculate member levels for a player.
 *
 * Recalculates member levels for all contexts the player is a member of.
 */
export const postDebugRecalculateMemberLevelsByPlayerId = <ThrowOnError extends boolean = false>(
  options: Options<PostDebugRecalculateMemberLevelsByPlayerIdData, ThrowOnError>,
) =>
  (options.client ?? client).post<PostDebugRecalculateMemberLevelsByPlayerIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/debug/recalculate-member-levels/{playerId}",
    ...options,
  })

/**
 * Recalculate player scores.
 *
 * Recalculates all player scores for the specified player.
 */
export const postDebugRecalculatePlayerScoresByPlayerId = <ThrowOnError extends boolean = false>(
  options: Options<PostDebugRecalculatePlayerScoresByPlayerIdData, ThrowOnError>,
) =>
  (options.client ?? client).post<PostDebugRecalculatePlayerScoresByPlayerIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/debug/recalculate-player-scores/{playerId}",
    ...options,
  })

/**
 * Delete all member point stats for a player.
 *
 * Deletes all member point stats for the specified player. USE WITH CAUTION!
 */
export const postDebugDeleteMemberPointStatsByPlayerId = <ThrowOnError extends boolean = false>(
  options: Options<PostDebugDeleteMemberPointStatsByPlayerIdData, ThrowOnError>,
) =>
  (options.client ?? client).post<PostDebugDeleteMemberPointStatsByPlayerIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/debug/delete-member-point-stats/{playerId}",
    ...options,
  })

/**
 * Login with BeatLeader
 *
 * Initiate the BeatLeader authentication flow with optional callback path.
 */
export const beatLeaderLogin = <ThrowOnError extends boolean = false>(
  options?: Options<BeatLeaderLoginData, ThrowOnError>,
) =>
  (options?.client ?? client).get<BeatLeaderLoginResponses, unknown, ThrowOnError>({
    url: "/auth/login/beatleader",
    ...options,
  })

/**
 * Login with Discord
 *
 * Initiate the Discord authentication flow with optional callback path.
 */
export const discordLogin = <ThrowOnError extends boolean = false>(options?: Options<DiscordLoginData, ThrowOnError>) =>
  (options?.client ?? client).get<DiscordLoginResponses, unknown, ThrowOnError>({
    url: "/auth/login/discord",
    ...options,
  })

/**
 * Initiate linking Discord from authentication flow.
 *
 * Initiate the Discord authentication flow to link Discord account to an existing authenticated user with optional callback path.
 */
export const discordLink = <ThrowOnError extends boolean = false>(options?: Options<DiscordLinkData, ThrowOnError>) =>
  (options?.client ?? client).get<DiscordLinkResponses, unknown, ThrowOnError>({
    url: "/auth/link/discord",
    ...options,
  })

/**
 * Link Discord account to existing authenticated user.
 *
 * Handles the callback from Discord to link Discord account to existing authenticated user.
 */
export const discordLinkCallback = <ThrowOnError extends boolean = false>(
  options?: Options<DiscordLinkCallbackData, ThrowOnError>,
) =>
  (options?.client ?? client).get<DiscordLinkCallbackResponses, DiscordLinkCallbackErrors, ThrowOnError>({
    url: "/auth/callback/link/discord",
    ...options,
  })

/**
 * Link Discord account to existing authenticated user with redirect.
 *
 * Handles the callback from Discord after authentication to link Discord account to an existing authenticated user and redirects to a specified path from the calling origin with ?type=discordLink&{error}&status as query params.
 */
export const discordLinkCallbackWithRedirect = <ThrowOnError extends boolean = false>(
  options: Options<DiscordLinkCallbackWithRedirectData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    DiscordLinkCallbackWithRedirectResponses,
    DiscordLinkCallbackWithRedirectErrors,
    ThrowOnError
  >({ url: "/auth/callback/link/discord/redirect", ...options })

/**
 * Get session token after authenticating with BeatLeader.
 *
 * Handles the callback from BeatLeader after authentication and returns a token.
 */
export const beatLeaderCallback = <ThrowOnError extends boolean = false>(
  options?: Options<BeatLeaderCallbackData, ThrowOnError>,
) =>
  (options?.client ?? client).get<BeatLeaderCallbackResponses, BeatLeaderCallbackErrors, ThrowOnError>({
    url: "/auth/callback/beatleader",
    ...options,
  })

/**
 * Get session token after authenticating with Discord.
 *
 * Handles the callback from Discord after authentication and returns a token.
 */
export const discordCallback = <ThrowOnError extends boolean = false>(
  options?: Options<DiscordCallbackData, ThrowOnError>,
) =>
  (options?.client ?? client).get<DiscordCallbackResponses, DiscordCallbackErrors, ThrowOnError>({
    url: "/auth/callback/discord",
    ...options,
  })

/**
 * Redirect with session token or error after Discord authentication.
 *
 * Handles the callback from Discord after authentication and redirects to a specified path from the calling origin with ?type=auth&{token/error}&status as query params.
 */
export const discordCallbackWithRedirect = <ThrowOnError extends boolean = false>(
  options: Options<DiscordCallbackWithRedirectData, ThrowOnError>,
) =>
  (options.client ?? client).get<DiscordCallbackWithRedirectResponses, DiscordCallbackWithRedirectErrors, ThrowOnError>(
    { url: "/auth/callback/discord/redirect", ...options },
  )

/**
 * Redirect with session token or error after BeatLeader authentication.
 *
 * Handles the callback from BeatLeader after authentication and redirects to a specified path from the calling origin with ?type=auth&{token/error}&status as query params.
 */
export const beatLeaderCallbackWithRedirect = <ThrowOnError extends boolean = false>(
  options: Options<BeatLeaderCallbackWithRedirectData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    BeatLeaderCallbackWithRedirectResponses,
    BeatLeaderCallbackWithRedirectErrors,
    ThrowOnError
  >({ url: "/auth/callback/beatleader/redirect", ...options })

/**
 * Log out the current user.
 */
export const logout = <ThrowOnError extends boolean = false>(options?: Options<LogoutData, ThrowOnError>) =>
  (options?.client ?? client).post<LogoutResponses, unknown, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/auth/logout",
    ...options,
  })
