// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:5042/" | (string & {})
}

export type AddMapVersion = {
  beatSaverKey: BeatSaverKey
  characteristic?: string
  difficulty?: EDifficulty
  playMode?: string
  order?: number | string
}

export type BeatLeaderScoreId = unknown

export type BeatSaverKey = string

export type BlLeaderboardId = string

export type Category = {
  id?: number | string
  guildId?: GuildId
  info?: CategoryInfo
}

export type CategoryInfo = {
  name?: string
  description?: string
}

export type ContextId = number

export type CreateCategory = {
  name?: string
  description?: string
}

export type CreateGuild = {
  info: GuildInfo
  requirements: GuildRequirements
}

export type CreateRankedMap = {
  /**
   * The map version that will be used as the base for the ranked map.
   */
  baseMapVersion: AddMapVersion
  requirements: RankedMapRequirements
  /**
   * Used to force a specific difficulty and/or accuracy star rating for the map.
   * If null, the star ratings will be calculated automatically by BeatLeader's ExMachina.
   */
  manualRating: ManualRating
  /**
   * The categories to assign the ranked map to.
   */
  categoryIds: Array<number | string>
  /**
   * The levels to assign the ranked map to (in case of RankedMapList levels).
   */
  levelIds: Array<number | string>
}

export type DiscordGuildId = string

export type EContextType = "Default" | "Tournament" | "Temporary"

export type EDifficulty = "Easy" | "Normal" | "Hard" | "Expert" | "ExpertPlus"

export type EGuildSorter = "Id" | "Popularity" | "Name" | "CreationDate" | "MapCount" | "MemberCount"

export type EGuildStatus = "Unverified" | "Verified" | "Featured" | "Private"

export type Ehmd =
  | "Unknown"
  | "Rift"
  | "Vive"
  | "VivePro"
  | "WMR"
  | "RiftS"
  | "Quest"
  | "PicoNeo3"
  | "PicoNeo2"
  | "VivePro2"
  | "ViveElite"
  | "Miramar"
  | "Pimax8K"
  | "Pimax5K"
  | "PimaxArtisan"
  | "HpReverb"
  | "SamsungWMR"
  | "QiyuDream"
  | "Disco"
  | "LenovoExplorer"
  | "AcerWMR"
  | "ViveFocus"
  | "Arpara"
  | "DellVisor"
  | "E3"
  | "ViveDvt"
  | "Glasses20"
  | "Hedy"
  | "Vaporeon"
  | "Huaweivr"
  | "AsusWMR"
  | "CloudXR"
  | "Vridge"
  | "Medion"
  | "PicoNeo4"
  | "QuestPro"
  | "PimaxCrystal"
  | "E4"
  | "Index"
  | "Controllable"
  | "BigScreenBeyond"
  | "Nolosonic"
  | "Hypereal"
  | "Varjoaero"
  | "PSVR2"
  | "Megane1"
  | "VarjoXR3"
  | "ViveCosmos"
  | "Quest2"
  | "Quest3"
  | "Quest3S"

export type EJoinState = "None" | "Joined" | "Requested" | "Invited" | "Refused" | "Banned"

export type EMemberSorters = "PlayerId" | "JoinState" | "CreatedAt" | "EditedAt" | "Permissions"

export type EMemberStatLeaderboardSorter = "Points" | "PassCount"

export type EModifiers = string

/**
 * Represents the order in which values will be sorted.
 */
export type EOrder = "Desc" | "Asc"

export type EPermission = string

export type EPlayerSorter = "Id" | "CreationDate"

export type ERankedMapLeaderboardSorter = "Points" | "EffectiveScore"

export type ERankedMapSorter = "Id" | "EditTime" | "CreationTime" | "DifficultyStar" | "AccuracyStar" | "Name"

export type ERankedScoreSorter = "Points" | "DifficultyStar" | "AccuracyStar" | "Score" | "Accuracy" | "ScoreTime"

export type EState = string

export type ESubscriptionTier = "None" | "Tier1" | "Tier2" | "Tier3"

export type Guild = {
  id: GuildId
  info: GuildInfo
  requirements: GuildRequirements
  status: EGuildStatus
  discordInfo: GuildDiscordInfo
}

export type GuildContext = {
  id?: number | string
  type?: EContextType
  info?: GuildContextInfo
  pointIds?: Array<number | string>
}

export type GuildContextInfo = {
  name?: string
  description?: string
}

export type GuildDiscordInfo = {
  mainDiscordGuildId: null | DiscordGuildId
  inviteCode: null | string
}

export type GuildExtended = {
  guild: Guild
  contexts: Array<GuildContext>
  pointsLite: Array<PointLite>
  categories: Array<Category>
}

export type GuildId = number

export type GuildInfo = {
  name: string
  smallName: string
  description: string
  color: number | string
  createdAt: string
}

export type GuildRequirements = {
  requireSubmission: boolean
  minRank: null | number | string
  maxRank: null | number | string
  minPP: null | number | string
  maxPP: null | number | string
  accountAgeUnix: null | number | string
}

export type GuildStatsResponse = {
  guildId?: number | string
  memberCount?: number | string
  rankedScoreCount?: number | string
}

export type HttpValidationProblemDetails = {
  type?: null | string
  title?: null | string
  status?: null | number | string
  detail?: null | string
  instance?: null | string
  errors?: {
    [key: string]: Array<string>
  }
  traceId?: string
}

export type IResult = {
  [key: string]: unknown
}

export type JsonPatchDocument = Array<
  | {
      op: "add" | "replace" | "test"
      path: string
      value: unknown
    }
  | {
      op: "move" | "copy"
      path: string
      from: string
    }
  | {
      op: "remove"
      path: string
    }
>

export type Level =
  | ({
      type?: "RankedMapList"
    } & LevelRankedMapListLevel)
  | ({
      type?: "DiffStar"
    } & LevelDiffStarLevel)
  | ({
      type?: "AccStar"
    } & LevelAccStarLevel)

export type LevelAccStarLevel = {
  type?: "AccStar"
  minStar: number | string
  requiredPassCount: number | string
  id: number | string
  guildId: GuildId
  contextId: ContextId
  categoryId: null | number | string
  info: LevelInfo
  order: number | string
  isLocking: boolean
}

export type LevelDiffStarLevel = {
  type?: "DiffStar"
  minStar: number | string
  requiredPassCount: number | string
  id: number | string
  guildId: GuildId
  contextId: ContextId
  categoryId: null | number | string
  info: LevelInfo
  order: number | string
  isLocking: boolean
}

export type LevelInfo = {
  name?: string
  color?: number | string
}

export type LevelRankedMapListLevel = {
  type?: "RankedMapList"
  requiredPassCount: number | string
  totalCount: number | string
  id: number | string
  guildId: GuildId
  contextId: ContextId
  categoryId: null | number | string
  info: LevelInfo
  order: number | string
  isLocking: boolean
}

export type ManualRating = {
  /**
   * When specified, the difficulty rating of the map won't be calculated by BeatLeader's ExMachina.
   */
  difficultyStar?: null | number | string
  /**
   * When specified, the accuracy rating of the map won't be calculated by BeatLeader's ExMachina.
   */
  accuracyStar?: null | number | string
}

export type MapVersion = {
  addedAt: string
  order: number | string
  song: Song
  difficulty: SongDifficulty
}

export type Member = {
  playerId?: number | string
  guildId?: GuildId
  initializedAt?: string
  editedAt?: string
  permissions?: EPermission
  joinState?: EJoinState
  priority?: number | string
}

export type MemberContextStat = {
  simplePointsWithRank?: Array<SimplePointWithRank>
  passCountWithRank?: PassCountWithRank
}

export type MemberLevelStat = {
  level?: Level
  isCompleted?: boolean
  isLocked?: boolean
  passCount?: null | number | string
}

export type MemberPointStat = {
  player?: Player
  points?: number | string
  passCount?: number | string
}

export type PagedListOfCategory = {
  data?: Array<Category>
  page?: number | string
  pageSize?: number | string
  totalCount?: number | string
  totalPages?: number | string
  hasPreviousPage?: boolean
  hasNextPage?: boolean
}

export type PagedListOfGuild = {
  data?: Array<Guild>
  page?: number | string
  pageSize?: number | string
  totalCount?: number | string
  totalPages?: number | string
  hasPreviousPage?: boolean
  hasNextPage?: boolean
}

export type PagedListOfMember = {
  data?: Array<Member>
  page?: number | string
  pageSize?: number | string
  totalCount?: number | string
  totalPages?: number | string
  hasPreviousPage?: boolean
  hasNextPage?: boolean
}

export type PagedListOfMemberPointStat = {
  data?: Array<MemberPointStat>
  page?: number | string
  pageSize?: number | string
  totalCount?: number | string
  totalPages?: number | string
  hasPreviousPage?: boolean
  hasNextPage?: boolean
}

export type PagedListOfPlayer = {
  data?: Array<Player>
  page?: number | string
  pageSize?: number | string
  totalCount?: number | string
  totalPages?: number | string
  hasPreviousPage?: boolean
  hasNextPage?: boolean
}

export type PagedListOfRankedMap = {
  data?: Array<RankedMap>
  page?: number | string
  pageSize?: number | string
  totalCount?: number | string
  totalPages?: number | string
  hasPreviousPage?: boolean
  hasNextPage?: boolean
}

export type PagedListOfRankedScore = {
  data?: Array<RankedScore>
  page?: number | string
  pageSize?: number | string
  totalCount?: number | string
  totalPages?: number | string
  hasPreviousPage?: boolean
  hasNextPage?: boolean
}

export type PagedListOfRankedScoreWithPlayer = {
  data?: Array<RankedScoreWithPlayer>
  page?: number | string
  pageSize?: number | string
  totalCount?: number | string
  totalPages?: number | string
  hasPreviousPage?: boolean
  hasNextPage?: boolean
}

export type PagedListOfRankedScoreWithRankedMap = {
  data?: Array<RankedScoreWithRankedMap>
  page?: number | string
  pageSize?: number | string
  totalCount?: number | string
  totalPages?: number | string
  hasPreviousPage?: boolean
  hasNextPage?: boolean
}

export type PassCountWithRank = {
  passCount?: number | string
  rank?: number | string
}

export type Player = {
  id?: PlayerId
  playerHardwareInfo?: PlayerHardwareInfo
  playerInfo?: PlayerInfo
  playerLinkedAccounts?: PlayerLinkedAccounts
  playerSubscriptionInfo?: PlayerSubscriptionInfo
  isManager?: boolean
}

export type PlayerExtended = {
  player?: Player
  members?: Array<Member>
}

export type PlayerHardwareInfo = {
  hmd?: string
  platform?: string
}

export type PlayerId = number

export type PlayerInfo = {
  username?: string
  avatarUrl?: string
  country?: string
  createdAt?: string
}

export type PlayerLinkedAccounts = {
  beatLeaderId?: string
  scoreSaberId?: null | string
  discordId?: null | string
}

export type PlayerSubscriptionInfo = {
  tier?: ESubscriptionTier
}

export type Playlist = {
  playlistTitle?: string
  playlistAuthor?: string
  playlistDescription?: string
  customData?: null | PlaylistCustomData
  songs?: Array<PlaylistSong>
  image?: null | string
}

export type PlaylistCustomData = {
  syncURL?: null | string
}

export type PlaylistDifficultyData = {
  characteristic?: string
  name?: string
}

export type PlaylistSong = {
  hash?: string
  difficulties?: Array<PlaylistDifficultyData>
}

export type PointLite = {
  id?: number | string
  guildContextId?: number | string
  name?: string
}

export type ProblemDetails = {
  type?: null | string
  title?: null | string
  status?: null | number | string
  detail?: null | string
  instance?: null | string
  traceId?: string
}

export type RankedMap = {
  id: number | string
  guildId: GuildId
  contextId: number | string
  info: RankedMapInfo
  requirements: RankedMapRequirements
  rating: RankedMapRating
  versions: Array<MapVersion>
  categoryIds: Array<number | string>
  levelIds: Array<number | string>
}

export type RankedMapInfo = {
  createdAt: string
  editedAt: string
}

export type RankedMapRating = {
  accStar: number | string
  diffStar: number | string
}

export type RankedMapRequirements = {
  needConfirmation?: boolean
  needFullCombo?: boolean
  maxPauseDurationSec?: null | number | string
  prohibitedModifiers?: EModifiers
  mandatoryModifiers?: EModifiers
  minAccuracy?: null | number | string
}

export type RankedScore = {
  id: number | string
  rankedMapId: number | string
  score: Score
  prevScore: null | Score
  state: EState
  rank: number | string
  rawPoints: number | string
  effectiveScore: number | string
}

export type RankedScoreWithPlayer = {
  rankedScore: RankedScore
  player: Player
}

export type RankedScoreWithRankedMap = {
  rankedScore: RankedScore
  rankedMap: RankedMap
}

export type RedirectHttpResult = {
  permanent?: boolean
  preserveMethod?: boolean
  url?: null | string
  acceptLocalUrlOnly?: boolean
}

export type Score =
  | ({
      type?: "BeatLeader"
    } & ScoreBeatLeaderScore)
  | ({
      type?: "ScoreSaber"
    } & ScoreScoreSaberScore)

export type ScoreBeatLeaderScore = {
  type?: "BeatLeader"
  beatLeaderScoreId: null | BeatLeaderScoreId
  id: number | string
  baseScore: number | string
  modifiers: EModifiers
  setAt: string
  maxCombo: null | number | string
  isFullCombo: boolean
  missedNotes: number | string
  badCuts: number | string
  hmd: Ehmd
}

export type ScoreSaberScoreId = unknown

export type ScoreScoreSaberScore = {
  type?: "ScoreSaber"
  scoreSaberScoreId: ScoreSaberScoreId
  deviceHmd: null | string
  deviceControllerLeft: null | string
  deviceControllerRight: null | string
  id: number | string
  baseScore: number | string
  modifiers: EModifiers
  setAt: string
  maxCombo: null | number | string
  isFullCombo: boolean
  missedNotes: number | string
  badCuts: number | string
  hmd: Ehmd
}

export type SimplePointWithRank = {
  pointId?: number | string
  categoryId?: null | number | string
  points?: number | string
  name?: string
  rank?: number | string
}

export type Song = {
  id: number | string
  hash: SongHash
  key: null | BeatSaverKey
  uploadedAt: string
  info: SongInfo
  stats: SongStats
}

export type SongDifficulty = {
  blLeaderboardId: null | BlLeaderboardId
  ssLeaderboardId: null | SsLeaderboardId
  difficulty: EDifficulty
  gameMode: string
  stats: SongDifficultyStats
}

export type SongDifficultyStats = {
  maxScore: number | string
  njs: number | string
  noteCount: number | string
  bombCount: number | string
  obstacleCount: number | string
  notesPerSecond: number | string
  duration: number | string
}

export type SongHash = string

export type SongInfo = {
  beatSaverName: string
  name: string
  subName: string
  authorName: string
  mapperName: string
}

export type SongStats = {
  bpm: number | string
  durationSec: number | string
  isAutoMapped: boolean
}

export type SsLeaderboardId = number

export type TokenResponse = {
  token?: string
}

export type UpdateCategory = {
  name?: string
  description?: string
}

export type GetLevelPlaylistData = {
  body?: never
  path: {
    levelId: number | string
  }
  query?: never
  url: "/levels/{levelId}/playlist"
}

export type GetLevelPlaylistErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails
}

export type GetLevelPlaylistError = GetLevelPlaylistErrors[keyof GetLevelPlaylistErrors]

export type GetLevelPlaylistResponses = {
  /**
   * OK
   */
  200: Playlist
}

export type GetLevelPlaylistResponse = GetLevelPlaylistResponses[keyof GetLevelPlaylistResponses]

export type GetPlayerRankedScoresData = {
  body?: never
  path: {
    playerId: string
    contextId: string
  }
  query?: {
    page?: number | string
    pageSize?: number | string
    sortBy?: ERankedScoreSorter
    order?: EOrder
    difficultyStarFrom?: number | string
    accuracyStarFrom?: number | string
    difficultyStarTo?: number | string
    accuracyStarTo?: number | string
    bpmFrom?: number | string
    bpmTo?: number | string
  }
  url: "/players/{playerId}/contexts/{contextId}/ranked-scores"
}

export type GetPlayerRankedScoresResponses = {
  /**
   * OK
   */
  200: PagedListOfRankedScore
}

export type GetPlayerRankedScoresResponse = GetPlayerRankedScoresResponses[keyof GetPlayerRankedScoresResponses]

export type GetPlayerAtMeRankedScoresData = {
  body?: never
  path: {
    contextId: string
  }
  query?: {
    page?: number | string
    pageSize?: number | string
    sortBy?: ERankedScoreSorter
    order?: EOrder
    difficultyStarFrom?: number | string
    accuracyStarFrom?: number | string
    difficultyStarTo?: number | string
    accuracyStarTo?: number | string
    bpmFrom?: number | string
    bpmTo?: number | string
  }
  url: "/players/@me/contexts/{contextId}/ranked-scores"
}

export type GetPlayerAtMeRankedScoresResponses = {
  /**
   * OK
   */
  200: PagedListOfRankedScore
}

export type GetPlayerAtMeRankedScoresResponse =
  GetPlayerAtMeRankedScoresResponses[keyof GetPlayerAtMeRankedScoresResponses]

export type GetPlayerRankedScoresWithRankedMapData = {
  body?: never
  path: {
    playerId: string
    contextId: string
  }
  query?: {
    page?: number | string
    pageSize?: number | string
    sortBy?: ERankedScoreSorter
    order?: EOrder
    difficultyStarFrom?: number | string
    accuracyStarFrom?: number | string
    difficultyStarTo?: number | string
    accuracyStarTo?: number | string
    bpmFrom?: number | string
    bpmTo?: number | string
  }
  url: "/players/{playerId}/contexts/{contextId}/ranked-scores-with-ranked-map"
}

export type GetPlayerRankedScoresWithRankedMapResponses = {
  /**
   * OK
   */
  200: PagedListOfRankedScoreWithRankedMap
}

export type GetPlayerRankedScoresWithRankedMapResponse =
  GetPlayerRankedScoresWithRankedMapResponses[keyof GetPlayerRankedScoresWithRankedMapResponses]

export type GetPlayerAtMeRankedScoresWithRankedMapData = {
  body?: never
  path: {
    contextId: string
  }
  query?: {
    page?: number | string
    pageSize?: number | string
    sortBy?: ERankedScoreSorter
    order?: EOrder
    difficultyStarFrom?: number | string
    accuracyStarFrom?: number | string
    difficultyStarTo?: number | string
    accuracyStarTo?: number | string
    bpmFrom?: number | string
    bpmTo?: number | string
  }
  url: "/players/@me/contexts/{contextId}/ranked-scores-with-ranked-map"
}

export type GetPlayerAtMeRankedScoresWithRankedMapResponses = {
  /**
   * OK
   */
  200: PagedListOfRankedScoreWithRankedMap
}

export type GetPlayerAtMeRankedScoresWithRankedMapResponse =
  GetPlayerAtMeRankedScoresWithRankedMapResponses[keyof GetPlayerAtMeRankedScoresWithRankedMapResponses]

export type GetRankedMapData = {
  body?: never
  path: {
    rankedMapId: string
  }
  query?: never
  url: "/ranked-maps/{rankedMapId}"
}

export type GetRankedMapErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails
}

export type GetRankedMapError = GetRankedMapErrors[keyof GetRankedMapErrors]

export type GetRankedMapResponses = {
  /**
   * OK
   */
  200: RankedMap
}

export type GetRankedMapResponse = GetRankedMapResponses[keyof GetRankedMapResponses]

export type GetRankedMapsData = {
  body?: never
  path: {
    contextId: ContextId
  }
  query?: {
    page?: number | string
    pageSize?: number | string
    search?: string
    sortBy?: ERankedMapSorter
    order?: EOrder
  }
  url: "/contexts/{contextId}/ranked-maps"
}

export type GetRankedMapsResponses = {
  /**
   * OK
   */
  200: PagedListOfRankedMap
}

export type GetRankedMapsResponse = GetRankedMapsResponses[keyof GetRankedMapsResponses]

export type CreateRankedMapData = {
  body: CreateRankedMap
  path: {
    contextId: string
  }
  query?: never
  url: "/contexts/{contextId}/ranked-maps"
}

export type CreateRankedMapErrors = {
  /**
   * Bad Request
   */
  400: HttpValidationProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
}

export type CreateRankedMapError = CreateRankedMapErrors[keyof CreateRankedMapErrors]

export type CreateRankedMapResponses = {
  /**
   * OK
   */
  200: RankedMap
}

export type CreateRankedMapResponse = CreateRankedMapResponses[keyof CreateRankedMapResponses]

export type GetPlayersData = {
  body?: never
  path?: never
  query?: {
    page?: number | string
    pageSize?: number | string
    search?: string
    sortBy?: EPlayerSorter
    order?: EOrder
  }
  url: "/players"
}

export type GetPlayersResponses = {
  /**
   * OK
   */
  200: PagedListOfPlayer
}

export type GetPlayersResponse = GetPlayersResponses[keyof GetPlayersResponses]

export type DeletePlayerData = {
  body?: never
  path: {
    playerId: string
  }
  query?: never
  url: "/players/{playerId}"
}

export type DeletePlayerErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails
}

export type DeletePlayerError = DeletePlayerErrors[keyof DeletePlayerErrors]

export type DeletePlayerResponses = {
  /**
   * No Content
   */
  204: void
}

export type DeletePlayerResponse = DeletePlayerResponses[keyof DeletePlayerResponses]

export type GetPlayerData = {
  body?: never
  path: {
    playerId: string
  }
  query?: never
  url: "/players/{playerId}"
}

export type GetPlayerErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails
}

export type GetPlayerError = GetPlayerErrors[keyof GetPlayerErrors]

export type GetPlayerResponses = {
  /**
   * OK
   */
  200: Player
}

export type GetPlayerResponse = GetPlayerResponses[keyof GetPlayerResponses]

export type GetPlayerAtMeData = {
  body?: never
  path?: never
  query?: never
  url: "/players/@me"
}

export type GetPlayerAtMeErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails
}

export type GetPlayerAtMeError = GetPlayerAtMeErrors[keyof GetPlayerAtMeErrors]

export type GetPlayerAtMeResponses = {
  /**
   * OK
   */
  200: Player
}

export type GetPlayerAtMeResponse = GetPlayerAtMeResponses[keyof GetPlayerAtMeResponses]

export type GetPlayerExtendedData = {
  body?: never
  path: {
    playerId: string
  }
  query?: never
  url: "/players/{playerId}/extended"
}

export type GetPlayerExtendedErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails
}

export type GetPlayerExtendedError = GetPlayerExtendedErrors[keyof GetPlayerExtendedErrors]

export type GetPlayerExtendedResponses = {
  /**
   * OK
   */
  200: PlayerExtended
}

export type GetPlayerExtendedResponse = GetPlayerExtendedResponses[keyof GetPlayerExtendedResponses]

export type GetPlayerExtendedAtMeData = {
  body?: never
  path?: never
  query?: never
  url: "/players/@me/extended"
}

export type GetPlayerExtendedAtMeErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails
}

export type GetPlayerExtendedAtMeError = GetPlayerExtendedAtMeErrors[keyof GetPlayerExtendedAtMeErrors]

export type GetPlayerExtendedAtMeResponses = {
  /**
   * OK
   */
  200: PlayerExtended
}

export type GetPlayerExtendedAtMeResponse = GetPlayerExtendedAtMeResponses[keyof GetPlayerExtendedAtMeResponses]

export type LookupPlayerByDiscordIdData = {
  body?: never
  path: {
    discordId: string
  }
  query?: never
  url: "/players/lookup/discord/{discordId}"
}

export type LookupPlayerByDiscordIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails
}

export type LookupPlayerByDiscordIdError = LookupPlayerByDiscordIdErrors[keyof LookupPlayerByDiscordIdErrors]

export type LookupPlayerByDiscordIdResponses = {
  /**
   * OK
   */
  200: PlayerId
}

export type LookupPlayerByDiscordIdResponse = LookupPlayerByDiscordIdResponses[keyof LookupPlayerByDiscordIdResponses]

export type GetContextPointRankedMapLeaderboardData = {
  body?: never
  path: {
    contextId: string
    pointId: string
    rankedMapId: string
  }
  query?: {
    page?: number | string
    pageSize?: number | string
    sortBy?: ERankedMapLeaderboardSorter
    order?: EOrder
  }
  url: "/contexts/{contextId}/points/{pointId}/ranked-maps/{rankedMapId}/leaderboard"
}

export type GetContextPointRankedMapLeaderboardResponses = {
  /**
   * OK
   */
  200: PagedListOfRankedScoreWithPlayer
}

export type GetContextPointRankedMapLeaderboardResponse =
  GetContextPointRankedMapLeaderboardResponses[keyof GetContextPointRankedMapLeaderboardResponses]

export type GetMemberPointStatLeaderboardData = {
  body?: never
  path: {
    contextId: string
    pointId: string
  }
  query?: {
    page?: number | string
    pageSize?: number | string
    sortBy?: EMemberStatLeaderboardSorter
    order?: EOrder
  }
  url: "/contexts/{contextId}/points/{pointId}/leaderboard"
}

export type GetMemberPointStatLeaderboardResponses = {
  /**
   * OK
   */
  200: PagedListOfMemberPointStat
}

export type GetMemberPointStatLeaderboardResponse =
  GetMemberPointStatLeaderboardResponses[keyof GetMemberPointStatLeaderboardResponses]

export type GetMemberCategoryPointStatLeaderboardData = {
  body?: never
  path: {
    contextId: string
    pointId: string
    categoryId: string
  }
  query?: {
    page?: number | string
    pageSize?: number | string
    sortBy?: EMemberStatLeaderboardSorter
    order?: EOrder
  }
  url: "/contexts/{contextId}/points/{pointId}/categories/{categoryId}/leaderboard"
}

export type GetMemberCategoryPointStatLeaderboardResponses = {
  /**
   * OK
   */
  200: PagedListOfMemberPointStat
}

export type GetMemberCategoryPointStatLeaderboardResponse =
  GetMemberCategoryPointStatLeaderboardResponses[keyof GetMemberCategoryPointStatLeaderboardResponses]

export type GetGuildsData = {
  body?: never
  path?: never
  query?: {
    page?: number | string
    pageSize?: number | string
    search?: string
    sortBy?: EGuildSorter
    order?: EOrder
  }
  url: "/guilds"
}

export type GetGuildsResponses = {
  /**
   * OK
   */
  200: PagedListOfGuild
}

export type GetGuildsResponse = GetGuildsResponses[keyof GetGuildsResponses]

export type CreateGuildData = {
  body: CreateGuild
  path?: never
  query?: never
  url: "/guilds"
}

export type CreateGuildErrors = {
  /**
   * Bad Request
   */
  400: HttpValidationProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
}

export type CreateGuildError = CreateGuildErrors[keyof CreateGuildErrors]

export type CreateGuildResponses = {
  /**
   * Created
   */
  201: Guild
}

export type CreateGuildResponse = CreateGuildResponses[keyof CreateGuildResponses]

export type DeleteGuildData = {
  body?: never
  path: {
    guildId: string
  }
  query?: never
  url: "/guilds/{guildId}"
}

export type DeleteGuildErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails
}

export type DeleteGuildError = DeleteGuildErrors[keyof DeleteGuildErrors]

export type DeleteGuildResponses = {
  /**
   * No Content
   */
  204: void
}

export type DeleteGuildResponse = DeleteGuildResponses[keyof DeleteGuildResponses]

export type GetGuildData = {
  body?: never
  path: {
    guildId: string
  }
  query?: never
  url: "/guilds/{guildId}"
}

export type GetGuildErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails
}

export type GetGuildError = GetGuildErrors[keyof GetGuildErrors]

export type GetGuildResponses = {
  /**
   * OK
   */
  200: Guild
}

export type GetGuildResponse = GetGuildResponses[keyof GetGuildResponses]

export type PatchGuildData = {
  body: JsonPatchDocument
  path: {
    guildId: string
  }
  query?: never
  url: "/guilds/{guildId}"
}

export type PatchGuildErrors = {
  /**
   * Bad Request
   */
  400: HttpValidationProblemDetails
}

export type PatchGuildError = PatchGuildErrors[keyof PatchGuildErrors]

export type PatchGuildResponses = {
  /**
   * OK
   */
  200: Guild
}

export type PatchGuildResponse = PatchGuildResponses[keyof PatchGuildResponses]

export type GetGuildExtendedData = {
  body?: never
  path: {
    guildId: string
  }
  query?: never
  url: "/guilds/{guildId}/extended"
}

export type GetGuildExtendedErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails
}

export type GetGuildExtendedError = GetGuildExtendedErrors[keyof GetGuildExtendedErrors]

export type GetGuildExtendedResponses = {
  /**
   * OK
   */
  200: GuildExtended
}

export type GetGuildExtendedResponse = GetGuildExtendedResponses[keyof GetGuildExtendedResponses]

export type GetGuildByDiscordIdData = {
  body?: never
  path: {
    discordGuildId: string
  }
  query?: never
  url: "/guilds/by-discord-id/{discordGuildId}"
}

export type GetGuildByDiscordIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails
}

export type GetGuildByDiscordIdError = GetGuildByDiscordIdErrors[keyof GetGuildByDiscordIdErrors]

export type GetGuildByDiscordIdResponses = {
  /**
   * OK
   */
  200: Guild
}

export type GetGuildByDiscordIdResponse = GetGuildByDiscordIdResponses[keyof GetGuildByDiscordIdResponses]

export type LookupGuildByDiscordGuildIdData = {
  body?: never
  path: {
    discordGuildId: string
  }
  query?: never
  url: "/guilds/lookup/discord/{discordGuildId}"
}

export type LookupGuildByDiscordGuildIdErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails
}

export type LookupGuildByDiscordGuildIdError =
  LookupGuildByDiscordGuildIdErrors[keyof LookupGuildByDiscordGuildIdErrors]

export type LookupGuildByDiscordGuildIdResponses = {
  /**
   * OK
   */
  200: GuildId
}

export type LookupGuildByDiscordGuildIdResponse =
  LookupGuildByDiscordGuildIdResponses[keyof LookupGuildByDiscordGuildIdResponses]

export type GetMembersData = {
  body?: never
  path: {
    guildId: string
  }
  query?: {
    page?: number | string
    pageSize?: number | string
    sortBy?: EMemberSorters
    order?: EOrder
  }
  url: "/guilds/{guildId}/members"
}

export type GetMembersResponses = {
  /**
   * OK
   */
  200: PagedListOfMember
}

export type GetMembersResponse = GetMembersResponses[keyof GetMembersResponses]

export type CurrentPlayerJoinGuildData = {
  body?: never
  path: {
    guildId: string
  }
  query?: never
  url: "/guilds/{guildId}/members"
}

export type CurrentPlayerJoinGuildErrors = {
  /**
   * Bad Request
   */
  400: HttpValidationProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: Member
}

export type CurrentPlayerJoinGuildError = CurrentPlayerJoinGuildErrors[keyof CurrentPlayerJoinGuildErrors]

export type CurrentPlayerJoinGuildResponses = {
  /**
   * OK
   */
  200: Member
  /**
   * Accepted
   */
  202: Member
}

export type CurrentPlayerJoinGuildResponse = CurrentPlayerJoinGuildResponses[keyof CurrentPlayerJoinGuildResponses]

export type GetMemberData = {
  body?: never
  path: {
    guildId: string
    playerId: string
  }
  query?: never
  url: "/guilds/{guildId}/members/{playerId}"
}

export type GetMemberErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails
}

export type GetMemberError = GetMemberErrors[keyof GetMemberErrors]

export type GetMemberResponses = {
  /**
   * OK
   */
  200: Member
}

export type GetMemberResponse = GetMemberResponses[keyof GetMemberResponses]

export type JoinGuildData = {
  body?: never
  path: {
    guildId: string
    playerId: string
  }
  query?: never
  url: "/guilds/{guildId}/members/{playerId}"
}

export type JoinGuildErrors = {
  /**
   * Bad Request
   */
  400: HttpValidationProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: Member
}

export type JoinGuildError = JoinGuildErrors[keyof JoinGuildErrors]

export type JoinGuildResponses = {
  /**
   * OK
   */
  200: Member
  /**
   * Accepted
   */
  202: Member
}

export type JoinGuildResponse = JoinGuildResponses[keyof JoinGuildResponses]

export type GetMemberLevelStatsData = {
  body?: never
  path: {
    contextId: string
    playerId: string
  }
  query?: never
  url: "/contexts/{contextId}/members/{playerId}/level-stats"
}

export type GetMemberLevelStatsResponses = {
  /**
   * OK
   */
  200: Array<MemberLevelStat>
}

export type GetMemberLevelStatsResponse = GetMemberLevelStatsResponses[keyof GetMemberLevelStatsResponses]

export type GetCurrentMemberLevelStatsData = {
  body?: never
  path: {
    contextId: string
  }
  query?: never
  url: "/contexts/{contextId}/members/@me/level-stats"
}

export type GetCurrentMemberLevelStatsResponses = {
  /**
   * OK
   */
  200: Array<MemberLevelStat>
}

export type GetCurrentMemberLevelStatsResponse =
  GetCurrentMemberLevelStatsResponses[keyof GetCurrentMemberLevelStatsResponses]

export type GetMemberContextStatsData = {
  body?: never
  path: {
    contextId: string
    playerId: string
  }
  query?: never
  url: "/contexts/{contextId}/members/{playerId}/context-stats"
}

export type GetMemberContextStatsErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails
}

export type GetMemberContextStatsError = GetMemberContextStatsErrors[keyof GetMemberContextStatsErrors]

export type GetMemberContextStatsResponses = {
  /**
   * OK
   */
  200: MemberContextStat
}

export type GetMemberContextStatsResponse = GetMemberContextStatsResponses[keyof GetMemberContextStatsResponses]

export type GetCurrentMemberContextStatsData = {
  body?: never
  path: {
    contextId: string
  }
  query?: never
  url: "/contexts/{contextId}/members/@me/context-stats"
}

export type GetCurrentMemberContextStatsErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails
}

export type GetCurrentMemberContextStatsError =
  GetCurrentMemberContextStatsErrors[keyof GetCurrentMemberContextStatsErrors]

export type GetCurrentMemberContextStatsResponses = {
  /**
   * OK
   */
  200: MemberContextStat
}

export type GetCurrentMemberContextStatsResponse =
  GetCurrentMemberContextStatsResponses[keyof GetCurrentMemberContextStatsResponses]

export type GetLevelsData = {
  body?: never
  path: {
    contextId: string
  }
  query?: {
    categoryId?: number | string
    hasCategory?: boolean
  }
  url: "/context/{contextId}/levels"
}

export type GetLevelsResponses = {
  /**
   * OK
   */
  200: Array<Level>
}

export type GetLevelsResponse = GetLevelsResponses[keyof GetLevelsResponses]

export type GetGuildStatsData = {
  body?: never
  path: {
    guildId: string
  }
  query?: never
  url: "/guilds/{guildId}/stats"
}

export type GetGuildStatsErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails
}

export type GetGuildStatsError = GetGuildStatsErrors[keyof GetGuildStatsErrors]

export type GetGuildStatsResponses = {
  /**
   * OK
   */
  200: GuildStatsResponse
}

export type GetGuildStatsResponse = GetGuildStatsResponses[keyof GetGuildStatsResponses]

export type GetCategoriesPaginatedData = {
  body?: never
  path?: never
  query?: {
    page?: number | string
    pageSize?: number | string
  }
  url: "/categories"
}

export type GetCategoriesPaginatedResponses = {
  /**
   * OK
   */
  200: PagedListOfCategory
}

export type GetCategoriesPaginatedResponse = GetCategoriesPaginatedResponses[keyof GetCategoriesPaginatedResponses]

export type GetCategoryData = {
  body?: never
  path: {
    categoryId: string
  }
  query?: never
  url: "/categories/{categoryId}"
}

export type GetCategoryErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails
}

export type GetCategoryError = GetCategoryErrors[keyof GetCategoryErrors]

export type GetCategoryResponses = {
  /**
   * OK
   */
  200: Category
}

export type GetCategoryResponse = GetCategoryResponses[keyof GetCategoryResponses]

export type GetCategoriesData = {
  body?: never
  path: {
    guildId: string
  }
  query?: never
  url: "/guilds/{guildId}/categories"
}

export type GetCategoriesResponses = {
  /**
   * OK
   */
  200: Array<Category>
}

export type GetCategoriesResponse = GetCategoriesResponses[keyof GetCategoriesResponses]

export type CreateCategoryData = {
  body: CreateCategory
  path: {
    guildId: string
  }
  query?: never
  url: "/guilds/{guildId}/categories"
}

export type CreateCategoryErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
}

export type CreateCategoryError = CreateCategoryErrors[keyof CreateCategoryErrors]

export type CreateCategoryResponses = {
  /**
   * Created
   */
  201: Category
}

export type CreateCategoryResponse = CreateCategoryResponses[keyof CreateCategoryResponses]

export type DeleteCategoryData = {
  body?: never
  path: {
    guildId: string
    categoryId: string
  }
  query?: never
  url: "/guilds/{guildId}/categories/{categoryId}"
}

export type DeleteCategoryErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails
}

export type DeleteCategoryError = DeleteCategoryErrors[keyof DeleteCategoryErrors]

export type DeleteCategoryResponses = {
  /**
   * No Content
   */
  204: void
}

export type DeleteCategoryResponse = DeleteCategoryResponses[keyof DeleteCategoryResponses]

export type UpdateCategoryData = {
  body: UpdateCategory
  path: {
    guildId: string
    categoryId: string
  }
  query?: never
  url: "/guilds/{guildId}/categories/{categoryId}"
}

export type UpdateCategoryResponses = {
  /**
   * OK
   */
  200: Category
}

export type UpdateCategoryResponse = UpdateCategoryResponses[keyof UpdateCategoryResponses]

export type ImportOldGuildSaberMapsBackgroundData = {
  body?: never
  path: {
    guildId: string
  }
  query: {
    count: number | string
    page: number | string
  }
  url: "/debug/import-old-gs-maps/{guildId}"
}

export type ImportOldGuildSaberMapsBackgroundErrors = {
  /**
   * Not Found
   */
  404: ProblemDetails
}

export type ImportOldGuildSaberMapsBackgroundError =
  ImportOldGuildSaberMapsBackgroundErrors[keyof ImportOldGuildSaberMapsBackgroundErrors]

export type ImportOldGuildSaberMapsBackgroundResponses = {
  /**
   * Accepted
   */
  202: IResult
}

export type ImportOldGuildSaberMapsBackgroundResponse =
  ImportOldGuildSaberMapsBackgroundResponses[keyof ImportOldGuildSaberMapsBackgroundResponses]

export type PostDebugImportBeatleaderScoresByPlayerIdData = {
  body?: never
  path: {
    playerId: string
  }
  query?: never
  url: "/debug/import-beatleader-scores/{playerId}"
}

export type PostDebugImportBeatleaderScoresByPlayerIdErrors = {
  /**
   * Not Found
   */
  404: string
}

export type PostDebugImportBeatleaderScoresByPlayerIdError =
  PostDebugImportBeatleaderScoresByPlayerIdErrors[keyof PostDebugImportBeatleaderScoresByPlayerIdErrors]

export type PostDebugImportBeatleaderScoresByPlayerIdResponses = {
  /**
   * Accepted
   */
  202: unknown
}

export type PostDebugImportScoresaberScoresByPlayerIdData = {
  body?: never
  path: {
    playerId: string
  }
  query?: never
  url: "/debug/import-scoresaber-scores/{playerId}"
}

export type PostDebugImportScoresaberScoresByPlayerIdErrors = {
  /**
   * Not Found
   */
  404: string
  /**
   * Unprocessable Entity
   */
  422: string
}

export type PostDebugImportScoresaberScoresByPlayerIdError =
  PostDebugImportScoresaberScoresByPlayerIdErrors[keyof PostDebugImportScoresaberScoresByPlayerIdErrors]

export type PostDebugImportScoresaberScoresByPlayerIdResponses = {
  /**
   * Accepted
   */
  202: unknown
}

export type PostDebugRemoveAllScoresData = {
  body?: never
  path?: never
  query?: never
  url: "/debug/remove-all-scores"
}

export type PostDebugRemoveAllScoresResponses = {
  /**
   * OK
   */
  200: unknown
}

export type PostDebugRemoveAllRankedScoresData = {
  body?: never
  path?: never
  query?: never
  url: "/debug/remove-all-ranked-scores"
}

export type PostDebugRemoveAllRankedScoresResponses = {
  /**
   * OK
   */
  200: unknown
}

export type PostDebugRemoveAllRankedMapsData = {
  body?: never
  path?: never
  query?: never
  url: "/debug/remove-all-ranked-maps"
}

export type PostDebugRemoveAllRankedMapsResponses = {
  /**
   * OK
   */
  200: unknown
}

export type PostDebugRecalculateMemberPointsByPlayerIdData = {
  body?: never
  path: {
    playerId: string
  }
  query?: never
  url: "/debug/recalculate-member-points/{playerId}"
}

export type PostDebugRecalculateMemberPointsByPlayerIdResponses = {
  /**
   * OK
   */
  200: unknown
}

export type PostDebugRecalculateMemberLevelsByPlayerIdData = {
  body?: never
  path: {
    playerId: string
  }
  query?: never
  url: "/debug/recalculate-member-levels/{playerId}"
}

export type PostDebugRecalculateMemberLevelsByPlayerIdResponses = {
  /**
   * OK
   */
  200: unknown
}

export type PostDebugRecalculatePlayerScoresByPlayerIdData = {
  body?: never
  path: {
    playerId: string
  }
  query?: never
  url: "/debug/recalculate-player-scores/{playerId}"
}

export type PostDebugRecalculatePlayerScoresByPlayerIdResponses = {
  /**
   * OK
   */
  200: unknown
}

export type PostDebugDeleteMemberPointStatsByPlayerIdData = {
  body?: never
  path: {
    playerId: string
  }
  query?: never
  url: "/debug/delete-member-point-stats/{playerId}"
}

export type PostDebugDeleteMemberPointStatsByPlayerIdResponses = {
  /**
   * OK
   */
  200: unknown
}

export type BeatLeaderLoginData = {
  body?: never
  path?: never
  query?: {
    returnUrl?: string
  }
  url: "/auth/login/beatleader"
}

export type BeatLeaderLoginResponses = {
  /**
   * OK
   */
  200: unknown
}

export type DiscordLoginData = {
  body?: never
  path?: never
  query?: {
    returnUrl?: string
  }
  url: "/auth/login/discord"
}

export type DiscordLoginResponses = {
  /**
   * OK
   */
  200: unknown
}

export type DiscordLinkData = {
  body?: never
  path?: never
  query?: {
    returnUrl?: string
  }
  url: "/auth/link/discord"
}

export type DiscordLinkResponses = {
  /**
   * OK
   */
  200: unknown
}

export type DiscordLinkCallbackData = {
  body?: never
  path?: never
  query?: never
  url: "/auth/callback/link/discord"
}

export type DiscordLinkCallbackErrors = {
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Unprocessable Entity
   */
  422: ProblemDetails
}

export type DiscordLinkCallbackError = DiscordLinkCallbackErrors[keyof DiscordLinkCallbackErrors]

export type DiscordLinkCallbackResponses = {
  /**
   * OK
   */
  200: RedirectHttpResult
}

export type DiscordLinkCallbackResponse = DiscordLinkCallbackResponses[keyof DiscordLinkCallbackResponses]

export type DiscordLinkCallbackWithRedirectData = {
  body?: never
  path?: never
  query: {
    returnUrl: string
  }
  url: "/auth/callback/link/discord/redirect"
}

export type DiscordLinkCallbackWithRedirectErrors = {
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Unprocessable Entity
   */
  422: ProblemDetails
}

export type DiscordLinkCallbackWithRedirectError =
  DiscordLinkCallbackWithRedirectErrors[keyof DiscordLinkCallbackWithRedirectErrors]

export type DiscordLinkCallbackWithRedirectResponses = {
  /**
   * OK
   */
  200: RedirectHttpResult
}

export type DiscordLinkCallbackWithRedirectResponse =
  DiscordLinkCallbackWithRedirectResponses[keyof DiscordLinkCallbackWithRedirectResponses]

export type BeatLeaderCallbackData = {
  body?: never
  path?: never
  query?: never
  url: "/auth/callback/beatleader"
}

export type BeatLeaderCallbackErrors = {
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Unprocessable Entity
   */
  422: ProblemDetails
  /**
   * Locked
   */
  423: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
}

export type BeatLeaderCallbackError = BeatLeaderCallbackErrors[keyof BeatLeaderCallbackErrors]

export type BeatLeaderCallbackResponses = {
  /**
   * OK
   */
  200: TokenResponse
}

export type BeatLeaderCallbackResponse = BeatLeaderCallbackResponses[keyof BeatLeaderCallbackResponses]

export type DiscordCallbackData = {
  body?: never
  path?: never
  query?: never
  url: "/auth/callback/discord"
}

export type DiscordCallbackErrors = {
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Unprocessable Entity
   */
  422: ProblemDetails
  /**
   * Locked
   */
  423: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
}

export type DiscordCallbackError = DiscordCallbackErrors[keyof DiscordCallbackErrors]

export type DiscordCallbackResponses = {
  /**
   * OK
   */
  200: TokenResponse
}

export type DiscordCallbackResponse = DiscordCallbackResponses[keyof DiscordCallbackResponses]

export type DiscordCallbackWithRedirectData = {
  body?: never
  path?: never
  query: {
    returnUrl: string
  }
  url: "/auth/callback/discord/redirect"
}

export type DiscordCallbackWithRedirectErrors = {
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Unprocessable Entity
   */
  422: ProblemDetails
  /**
   * Locked
   */
  423: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
}

export type DiscordCallbackWithRedirectError =
  DiscordCallbackWithRedirectErrors[keyof DiscordCallbackWithRedirectErrors]

export type DiscordCallbackWithRedirectResponses = {
  /**
   * OK
   */
  200: RedirectHttpResult
}

export type DiscordCallbackWithRedirectResponse =
  DiscordCallbackWithRedirectResponses[keyof DiscordCallbackWithRedirectResponses]

export type BeatLeaderCallbackWithRedirectData = {
  body?: never
  path?: never
  query: {
    returnUrl: string
  }
  url: "/auth/callback/beatleader/redirect"
}

export type BeatLeaderCallbackWithRedirectErrors = {
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Unprocessable Entity
   */
  422: ProblemDetails
  /**
   * Locked
   */
  423: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
}

export type BeatLeaderCallbackWithRedirectError =
  BeatLeaderCallbackWithRedirectErrors[keyof BeatLeaderCallbackWithRedirectErrors]

export type BeatLeaderCallbackWithRedirectResponses = {
  /**
   * OK
   */
  200: RedirectHttpResult
}

export type BeatLeaderCallbackWithRedirectResponse =
  BeatLeaderCallbackWithRedirectResponses[keyof BeatLeaderCallbackWithRedirectResponses]

export type LogoutData = {
  body?: never
  path?: never
  query?: never
  url: "/auth/logout"
}

export type LogoutResponses = {
  /**
   * OK
   */
  200: unknown
}
