global using static CSharpFunctionalExtensions.Maybe;
global using static CSharpFunctionalExtensions.Result;
global using static CSharpFunctionalExtensions.UnitResult;
global using static GuildSaber.CSharpClient.PolyFill;
global using GuildId = GuildSaber.Common.StrongTypes.GuildId;
global using ContextId = GuildSaber.Common.StrongTypes.ContextId;
global using PlayerId = GuildSaber.Common.StrongTypes.PlayerId;
global using CategoryId = GuildSaber.Common.StrongTypes.CategoryId;
global using DiscordId = GuildSaber.Common.StrongTypes.DiscordId;
global using DiscordGuildId = GuildSaber.Common.StrongTypes.DiscordGuildId;