// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query"

import { client } from "../client.gen"
import {
  beatLeaderCallback,
  beatLeaderCallbackWithRedirect,
  beatLeaderLogin,
  createCategory,
  createGuild,
  createRankedMap,
  deleteCategory,
  deleteGuild,
  deletePlayer,
  discordCallback,
  discordCallbackWithRedirect,
  discordLink,
  discordLinkCallback,
  discordLinkCallbackWithRedirect,
  discordLogin,
  getCategories,
  getCategoriesPaginated,
  getCategory,
  getContextPointRankedMapLeaderboard,
  getCurrentMemberContextStats,
  getCurrentMemberLevelStats,
  getGuild,
  getGuildByDiscordId,
  getGuildExtended,
  getGuilds,
  getGuildStats,
  getLevelPlaylist,
  getLevels,
  getMember,
  getMemberCategoryPointStatLeaderboard,
  getMemberContextStats,
  getMemberLevelStats,
  getMemberPointStatLeaderboard,
  getMembers,
  getPlayer,
  getPlayerAtMe,
  getPlayerExtended,
  getPlayerExtendedAtMe,
  getPlayerRankedScores,
  getPlayerRankedScoresAtMe,
  getPlayerRankedScoresWithRankedMap,
  getPlayerRankedScoresWithRankedMapAtMe,
  getPlayers,
  getRankedMap,
  getRankedMaps,
  importOldGuildSaberMapsBackground,
  joinGuild,
  joinGuildAtMe,
  logout,
  logoutAll,
  logoutAllWithRedirect,
  logoutWithRedirect,
  lookupGuildByDiscordGuildId,
  lookupPlayerByDiscordId,
  type Options,
  patchGuild,
  postDebugDeleteMemberPointStatsByPlayerId,
  postDebugImportBeatleaderScoresByPlayerId,
  postDebugImportScoresaberScoresByPlayerId,
  postDebugRecalculateMemberLevelsByPlayerId,
  postDebugRecalculateMemberPointsByPlayerId,
  postDebugRecalculatePlayerScoresByPlayerId,
  postDebugRemoveAllRankedMaps,
  postDebugRemoveAllRankedScores,
  postDebugRemoveAllScores,
  updateCategory,
} from "../sdk.gen"
import type {
  BeatLeaderCallbackData,
  BeatLeaderCallbackError,
  BeatLeaderCallbackResponse,
  BeatLeaderCallbackWithRedirectData,
  BeatLeaderCallbackWithRedirectError,
  BeatLeaderCallbackWithRedirectResponse,
  BeatLeaderLoginData,
  CreateCategoryData,
  CreateCategoryError,
  CreateCategoryResponse,
  CreateGuildData,
  CreateGuildError,
  CreateGuildResponse,
  CreateRankedMapData,
  CreateRankedMapError,
  CreateRankedMapResponse,
  DeleteCategoryData,
  DeleteCategoryError,
  DeleteCategoryResponse,
  DeleteGuildData,
  DeleteGuildError,
  DeleteGuildResponse,
  DeletePlayerData,
  DeletePlayerError,
  DeletePlayerResponse,
  DiscordCallbackData,
  DiscordCallbackError,
  DiscordCallbackResponse,
  DiscordCallbackWithRedirectData,
  DiscordCallbackWithRedirectError,
  DiscordCallbackWithRedirectResponse,
  DiscordLinkCallbackData,
  DiscordLinkCallbackError,
  DiscordLinkCallbackResponse,
  DiscordLinkCallbackWithRedirectData,
  DiscordLinkCallbackWithRedirectError,
  DiscordLinkCallbackWithRedirectResponse,
  DiscordLinkData,
  DiscordLoginData,
  GetCategoriesData,
  GetCategoriesPaginatedData,
  GetCategoriesPaginatedResponse,
  GetCategoriesResponse,
  GetCategoryData,
  GetCategoryError,
  GetCategoryResponse,
  GetContextPointRankedMapLeaderboardData,
  GetContextPointRankedMapLeaderboardResponse,
  GetCurrentMemberContextStatsData,
  GetCurrentMemberContextStatsError,
  GetCurrentMemberContextStatsResponse,
  GetCurrentMemberLevelStatsData,
  GetCurrentMemberLevelStatsResponse,
  GetGuildByDiscordIdData,
  GetGuildByDiscordIdError,
  GetGuildByDiscordIdResponse,
  GetGuildData,
  GetGuildError,
  GetGuildExtendedData,
  GetGuildExtendedError,
  GetGuildExtendedResponse,
  GetGuildResponse,
  GetGuildsData,
  GetGuildsResponse,
  GetGuildStatsData,
  GetGuildStatsError,
  GetGuildStatsResponse,
  GetLevelPlaylistData,
  GetLevelPlaylistError,
  GetLevelPlaylistResponse,
  GetLevelsData,
  GetLevelsResponse,
  GetMemberCategoryPointStatLeaderboardData,
  GetMemberCategoryPointStatLeaderboardResponse,
  GetMemberContextStatsData,
  GetMemberContextStatsError,
  GetMemberContextStatsResponse,
  GetMemberData,
  GetMemberError,
  GetMemberLevelStatsData,
  GetMemberLevelStatsResponse,
  GetMemberPointStatLeaderboardData,
  GetMemberPointStatLeaderboardResponse,
  GetMemberResponse,
  GetMembersData,
  GetMembersResponse,
  GetPlayerAtMeData,
  GetPlayerAtMeError,
  GetPlayerAtMeResponse,
  GetPlayerData,
  GetPlayerError,
  GetPlayerExtendedAtMeData,
  GetPlayerExtendedAtMeError,
  GetPlayerExtendedAtMeResponse,
  GetPlayerExtendedData,
  GetPlayerExtendedError,
  GetPlayerExtendedResponse,
  GetPlayerRankedScoresAtMeData,
  GetPlayerRankedScoresAtMeResponse,
  GetPlayerRankedScoresData,
  GetPlayerRankedScoresResponse,
  GetPlayerRankedScoresWithRankedMapAtMeData,
  GetPlayerRankedScoresWithRankedMapAtMeResponse,
  GetPlayerRankedScoresWithRankedMapData,
  GetPlayerRankedScoresWithRankedMapResponse,
  GetPlayerResponse,
  GetPlayersData,
  GetPlayersResponse,
  GetRankedMapData,
  GetRankedMapError,
  GetRankedMapResponse,
  GetRankedMapsData,
  GetRankedMapsResponse,
  ImportOldGuildSaberMapsBackgroundData,
  ImportOldGuildSaberMapsBackgroundError,
  ImportOldGuildSaberMapsBackgroundResponse,
  JoinGuildAtMeData,
  JoinGuildAtMeError,
  JoinGuildAtMeResponse,
  JoinGuildData,
  JoinGuildError,
  JoinGuildResponse,
  LogoutAllData,
  LogoutAllError,
  LogoutAllResponse,
  LogoutAllWithRedirectData,
  LogoutData,
  LogoutError,
  LogoutResponse,
  LogoutWithRedirectData,
  LookupGuildByDiscordGuildIdData,
  LookupGuildByDiscordGuildIdError,
  LookupGuildByDiscordGuildIdResponse,
  LookupPlayerByDiscordIdData,
  LookupPlayerByDiscordIdError,
  LookupPlayerByDiscordIdResponse,
  PatchGuildData,
  PatchGuildError,
  PatchGuildResponse,
  PostDebugDeleteMemberPointStatsByPlayerIdData,
  PostDebugImportBeatleaderScoresByPlayerIdData,
  PostDebugImportBeatleaderScoresByPlayerIdError,
  PostDebugImportScoresaberScoresByPlayerIdData,
  PostDebugImportScoresaberScoresByPlayerIdError,
  PostDebugRecalculateMemberLevelsByPlayerIdData,
  PostDebugRecalculateMemberPointsByPlayerIdData,
  PostDebugRecalculatePlayerScoresByPlayerIdData,
  PostDebugRemoveAllRankedMapsData,
  PostDebugRemoveAllRankedScoresData,
  PostDebugRemoveAllScoresData,
  UpdateCategoryData,
  UpdateCategoryResponse,
} from "../types.gen"

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string
    _infinite?: boolean
    tags?: ReadonlyArray<string>
  },
]

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0]
  if (infinite) {
    params._infinite = infinite
  }
  if (tags) {
    params.tags = tags
  }
  if (options?.body) {
    params.body = options.body
  }
  if (options?.headers) {
    params.headers = options.headers
  }
  if (options?.path) {
    params.path = options.path
  }
  if (options?.query) {
    params.query = options.query
  }
  return [params]
}

export const getLevelPlaylistQueryKey = (options: Options<GetLevelPlaylistData>) =>
  createQueryKey("getLevelPlaylist", options)

/**
 * Get the playlist for a ranked map list level.
 *
 * Get the playlist associated with a ranked map list level by its Id.
 */
export const getLevelPlaylistOptions = (options: Options<GetLevelPlaylistData>) =>
  queryOptions<
    GetLevelPlaylistResponse,
    GetLevelPlaylistError,
    GetLevelPlaylistResponse,
    ReturnType<typeof getLevelPlaylistQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getLevelPlaylist({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getLevelPlaylistQueryKey(options),
  })

export const getPlayerRankedScoresQueryKey = (options: Options<GetPlayerRankedScoresData>) =>
  createQueryKey("getPlayerRankedScores", options)

/**
 * Get all ranked scores of a player paginated
 *
 * Get all ranked scores of a specific player by their Id, with optional sorting.
 */
export const getPlayerRankedScoresOptions = (options: Options<GetPlayerRankedScoresData>) =>
  queryOptions<
    GetPlayerRankedScoresResponse,
    DefaultError,
    GetPlayerRankedScoresResponse,
    ReturnType<typeof getPlayerRankedScoresQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getPlayerRankedScores({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getPlayerRankedScoresQueryKey(options),
  })

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], "body" | "headers" | "path" | "query">>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = { ...queryKey[0] }
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    }
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    }
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    }
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    }
  }
  return params as unknown as typeof page
}

export const getPlayerRankedScoresInfiniteQueryKey = (
  options: Options<GetPlayerRankedScoresData>,
): QueryKey<Options<GetPlayerRankedScoresData>> => createQueryKey("getPlayerRankedScores", options, true)

/**
 * Get all ranked scores of a player paginated
 *
 * Get all ranked scores of a specific player by their Id, with optional sorting.
 */
export const getPlayerRankedScoresInfiniteOptions = (options: Options<GetPlayerRankedScoresData>) =>
  infiniteQueryOptions<
    GetPlayerRankedScoresResponse,
    DefaultError,
    InfiniteData<GetPlayerRankedScoresResponse>,
    QueryKey<Options<GetPlayerRankedScoresData>>,
    number | string | Pick<QueryKey<Options<GetPlayerRankedScoresData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetPlayerRankedScoresData>>[0], "body" | "headers" | "path" | "query"> =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await getPlayerRankedScores({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: getPlayerRankedScoresInfiniteQueryKey(options),
    },
  )

export const getPlayerRankedScoresAtMeQueryKey = (options: Options<GetPlayerRankedScoresAtMeData>) =>
  createQueryKey("getPlayerRankedScoresAtMe", options)

/**
 * Get current player's ranked scores paginated
 *
 * Get the current player's ranked scores using their player id from claims, with optional sorting.
 */
export const getPlayerRankedScoresAtMeOptions = (options: Options<GetPlayerRankedScoresAtMeData>) =>
  queryOptions<
    GetPlayerRankedScoresAtMeResponse,
    DefaultError,
    GetPlayerRankedScoresAtMeResponse,
    ReturnType<typeof getPlayerRankedScoresAtMeQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getPlayerRankedScoresAtMe({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getPlayerRankedScoresAtMeQueryKey(options),
  })

export const getPlayerRankedScoresAtMeInfiniteQueryKey = (
  options: Options<GetPlayerRankedScoresAtMeData>,
): QueryKey<Options<GetPlayerRankedScoresAtMeData>> => createQueryKey("getPlayerRankedScoresAtMe", options, true)

/**
 * Get current player's ranked scores paginated
 *
 * Get the current player's ranked scores using their player id from claims, with optional sorting.
 */
export const getPlayerRankedScoresAtMeInfiniteOptions = (options: Options<GetPlayerRankedScoresAtMeData>) =>
  infiniteQueryOptions<
    GetPlayerRankedScoresAtMeResponse,
    DefaultError,
    InfiniteData<GetPlayerRankedScoresAtMeResponse>,
    QueryKey<Options<GetPlayerRankedScoresAtMeData>>,
    number | string | Pick<QueryKey<Options<GetPlayerRankedScoresAtMeData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetPlayerRankedScoresAtMeData>>[0], "body" | "headers" | "path" | "query"> =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await getPlayerRankedScoresAtMe({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: getPlayerRankedScoresAtMeInfiniteQueryKey(options),
    },
  )

export const getPlayerRankedScoresWithRankedMapQueryKey = (options: Options<GetPlayerRankedScoresWithRankedMapData>) =>
  createQueryKey("getPlayerRankedScoresWithRankedMap", options)

/**
 * Get all ranked scores of a player with ranked map paginated
 *
 * Get all ranked scores of a specific player by their Id along with ranked map, with optional sorting.
 */
export const getPlayerRankedScoresWithRankedMapOptions = (options: Options<GetPlayerRankedScoresWithRankedMapData>) =>
  queryOptions<
    GetPlayerRankedScoresWithRankedMapResponse,
    DefaultError,
    GetPlayerRankedScoresWithRankedMapResponse,
    ReturnType<typeof getPlayerRankedScoresWithRankedMapQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getPlayerRankedScoresWithRankedMap({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getPlayerRankedScoresWithRankedMapQueryKey(options),
  })

export const getPlayerRankedScoresWithRankedMapInfiniteQueryKey = (
  options: Options<GetPlayerRankedScoresWithRankedMapData>,
): QueryKey<Options<GetPlayerRankedScoresWithRankedMapData>> =>
  createQueryKey("getPlayerRankedScoresWithRankedMap", options, true)

/**
 * Get all ranked scores of a player with ranked map paginated
 *
 * Get all ranked scores of a specific player by their Id along with ranked map, with optional sorting.
 */
export const getPlayerRankedScoresWithRankedMapInfiniteOptions = (
  options: Options<GetPlayerRankedScoresWithRankedMapData>,
) =>
  infiniteQueryOptions<
    GetPlayerRankedScoresWithRankedMapResponse,
    DefaultError,
    InfiniteData<GetPlayerRankedScoresWithRankedMapResponse>,
    QueryKey<Options<GetPlayerRankedScoresWithRankedMapData>>,
    | number
    | string
    | Pick<QueryKey<Options<GetPlayerRankedScoresWithRankedMapData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetPlayerRankedScoresWithRankedMapData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await getPlayerRankedScoresWithRankedMap({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: getPlayerRankedScoresWithRankedMapInfiniteQueryKey(options),
    },
  )

export const getPlayerRankedScoresWithRankedMapAtMeQueryKey = (
  options: Options<GetPlayerRankedScoresWithRankedMapAtMeData>,
) => createQueryKey("getPlayerRankedScoresWithRankedMapAtMe", options)

/**
 * Get current player's ranked scores with ranked map paginated
 *
 * Get the current player's ranked scores along with ranked map using their player id from claims, with optional sorting.
 */
export const getPlayerRankedScoresWithRankedMapAtMeOptions = (
  options: Options<GetPlayerRankedScoresWithRankedMapAtMeData>,
) =>
  queryOptions<
    GetPlayerRankedScoresWithRankedMapAtMeResponse,
    DefaultError,
    GetPlayerRankedScoresWithRankedMapAtMeResponse,
    ReturnType<typeof getPlayerRankedScoresWithRankedMapAtMeQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getPlayerRankedScoresWithRankedMapAtMe({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getPlayerRankedScoresWithRankedMapAtMeQueryKey(options),
  })

export const getPlayerRankedScoresWithRankedMapAtMeInfiniteQueryKey = (
  options: Options<GetPlayerRankedScoresWithRankedMapAtMeData>,
): QueryKey<Options<GetPlayerRankedScoresWithRankedMapAtMeData>> =>
  createQueryKey("getPlayerRankedScoresWithRankedMapAtMe", options, true)

/**
 * Get current player's ranked scores with ranked map paginated
 *
 * Get the current player's ranked scores along with ranked map using their player id from claims, with optional sorting.
 */
export const getPlayerRankedScoresWithRankedMapAtMeInfiniteOptions = (
  options: Options<GetPlayerRankedScoresWithRankedMapAtMeData>,
) =>
  infiniteQueryOptions<
    GetPlayerRankedScoresWithRankedMapAtMeResponse,
    DefaultError,
    InfiniteData<GetPlayerRankedScoresWithRankedMapAtMeResponse>,
    QueryKey<Options<GetPlayerRankedScoresWithRankedMapAtMeData>>,
    | number
    | string
    | Pick<QueryKey<Options<GetPlayerRankedScoresWithRankedMapAtMeData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetPlayerRankedScoresWithRankedMapAtMeData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await getPlayerRankedScoresWithRankedMapAtMe({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: getPlayerRankedScoresWithRankedMapAtMeInfiniteQueryKey(options),
    },
  )

export const getRankedMapQueryKey = (options: Options<GetRankedMapData>) => createQueryKey("getRankedMap", options)

/**
 * Get a ranked map.
 *
 * Get a ranked map in the server by its Id.
 */
export const getRankedMapOptions = (options: Options<GetRankedMapData>) =>
  queryOptions<GetRankedMapResponse, GetRankedMapError, GetRankedMapResponse, ReturnType<typeof getRankedMapQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getRankedMap({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getRankedMapQueryKey(options),
  })

export const getRankedMapsQueryKey = (options: Options<GetRankedMapsData>) => createQueryKey("getRankedMaps", options)

/**
 * Get ranked maps for a context.
 *
 * Get ranked maps for a context by its Id, with optional search and sorting.
 */
export const getRankedMapsOptions = (options: Options<GetRankedMapsData>) =>
  queryOptions<GetRankedMapsResponse, DefaultError, GetRankedMapsResponse, ReturnType<typeof getRankedMapsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getRankedMaps({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getRankedMapsQueryKey(options),
  })

export const getRankedMapsInfiniteQueryKey = (
  options: Options<GetRankedMapsData>,
): QueryKey<Options<GetRankedMapsData>> => createQueryKey("getRankedMaps", options, true)

/**
 * Get ranked maps for a context.
 *
 * Get ranked maps for a context by its Id, with optional search and sorting.
 */
export const getRankedMapsInfiniteOptions = (options: Options<GetRankedMapsData>) =>
  infiniteQueryOptions<
    GetRankedMapsResponse,
    DefaultError,
    InfiniteData<GetRankedMapsResponse>,
    QueryKey<Options<GetRankedMapsData>>,
    number | string | Pick<QueryKey<Options<GetRankedMapsData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetRankedMapsData>>[0], "body" | "headers" | "path" | "query"> =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await getRankedMaps({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: getRankedMapsInfiniteQueryKey(options),
    },
  )

/**
 * Create a ranked map for a context.
 *
 *     This endpoint:
 * * Returns 200 OK with ranked map details when created successfully.
 * * Returns 401 Unauthorized when the guild has reached its maximum number of ranked maps.
 * * Returns 400 Bad Request with validation details when validation fails.
 * * Returns 404 Not Found when the map is not found on BeatSaver.
 * * Returns 429 Too Many Requests when rate limited by BeatSaver API.
 * * Returns 500 Internal Server Error when BeatSaver API fails.
 */
export const createRankedMapMutation = (
  options?: Partial<Options<CreateRankedMapData>>,
): UseMutationOptions<CreateRankedMapResponse, CreateRankedMapError, Options<CreateRankedMapData>> => {
  const mutationOptions: UseMutationOptions<
    CreateRankedMapResponse,
    CreateRankedMapError,
    Options<CreateRankedMapData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createRankedMap({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getPlayersQueryKey = (options?: Options<GetPlayersData>) => createQueryKey("getPlayers", options)

/**
 * Get all players paginated
 *
 * Get all players in the server, with optional search and sorting.
 */
export const getPlayersOptions = (options?: Options<GetPlayersData>) =>
  queryOptions<GetPlayersResponse, DefaultError, GetPlayersResponse, ReturnType<typeof getPlayersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getPlayers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getPlayersQueryKey(options),
  })

export const getPlayersInfiniteQueryKey = (options?: Options<GetPlayersData>): QueryKey<Options<GetPlayersData>> =>
  createQueryKey("getPlayers", options, true)

/**
 * Get all players paginated
 *
 * Get all players in the server, with optional search and sorting.
 */
export const getPlayersInfiniteOptions = (options?: Options<GetPlayersData>) =>
  infiniteQueryOptions<
    GetPlayersResponse,
    DefaultError,
    InfiniteData<GetPlayersResponse>,
    QueryKey<Options<GetPlayersData>>,
    number | string | Pick<QueryKey<Options<GetPlayersData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetPlayersData>>[0], "body" | "headers" | "path" | "query"> =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await getPlayers({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: getPlayersInfiniteQueryKey(options),
    },
  )

/**
 * Delete a player
 *
 * Delete a specific player by their Id.
 */
export const deletePlayerMutation = (
  options?: Partial<Options<DeletePlayerData>>,
): UseMutationOptions<DeletePlayerResponse, DeletePlayerError, Options<DeletePlayerData>> => {
  const mutationOptions: UseMutationOptions<DeletePlayerResponse, DeletePlayerError, Options<DeletePlayerData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await deletePlayer({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getPlayerQueryKey = (options: Options<GetPlayerData>) => createQueryKey("getPlayer", options)

/**
 * Get a player
 *
 * Get a specific player by their Id.
 */
export const getPlayerOptions = (options: Options<GetPlayerData>) =>
  queryOptions<GetPlayerResponse, GetPlayerError, GetPlayerResponse, ReturnType<typeof getPlayerQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getPlayer({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getPlayerQueryKey(options),
  })

export const getPlayerAtMeQueryKey = (options?: Options<GetPlayerAtMeData>) => createQueryKey("getPlayerAtMe", options)

/**
 * Get current player
 *
 * Get the current player information.
 */
export const getPlayerAtMeOptions = (options?: Options<GetPlayerAtMeData>) =>
  queryOptions<
    GetPlayerAtMeResponse,
    GetPlayerAtMeError,
    GetPlayerAtMeResponse,
    ReturnType<typeof getPlayerAtMeQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getPlayerAtMe({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getPlayerAtMeQueryKey(options),
  })

export const getPlayerExtendedQueryKey = (options: Options<GetPlayerExtendedData>) =>
  createQueryKey("getPlayerExtended", options)

/**
 * Get a player with extended information
 *
 * Get a specific player with extended information by their Id. Which includes additional fields like guilds and permissions.
 */
export const getPlayerExtendedOptions = (options: Options<GetPlayerExtendedData>) =>
  queryOptions<
    GetPlayerExtendedResponse,
    GetPlayerExtendedError,
    GetPlayerExtendedResponse,
    ReturnType<typeof getPlayerExtendedQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getPlayerExtended({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getPlayerExtendedQueryKey(options),
  })

export const getPlayerExtendedAtMeQueryKey = (options?: Options<GetPlayerExtendedAtMeData>) =>
  createQueryKey("getPlayerExtendedAtMe", options)

/**
 * Get current player with extended information
 *
 * Get the current player information alongside their guilds and permissions.
 */
export const getPlayerExtendedAtMeOptions = (options?: Options<GetPlayerExtendedAtMeData>) =>
  queryOptions<
    GetPlayerExtendedAtMeResponse,
    GetPlayerExtendedAtMeError,
    GetPlayerExtendedAtMeResponse,
    ReturnType<typeof getPlayerExtendedAtMeQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getPlayerExtendedAtMe({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getPlayerExtendedAtMeQueryKey(options),
  })

export const lookupPlayerByDiscordIdQueryKey = (options: Options<LookupPlayerByDiscordIdData>) =>
  createQueryKey("lookupPlayerByDiscordId", options)

/**
 * Lookup player ID by Discord ID
 *
 * Resolve a player's ID from their linked Discord account ID.
 */
export const lookupPlayerByDiscordIdOptions = (options: Options<LookupPlayerByDiscordIdData>) =>
  queryOptions<
    LookupPlayerByDiscordIdResponse,
    LookupPlayerByDiscordIdError,
    LookupPlayerByDiscordIdResponse,
    ReturnType<typeof lookupPlayerByDiscordIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await lookupPlayerByDiscordId({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: lookupPlayerByDiscordIdQueryKey(options),
  })

export const getContextPointRankedMapLeaderboardQueryKey = (
  options: Options<GetContextPointRankedMapLeaderboardData>,
) => createQueryKey("getContextPointRankedMapLeaderboard", options)

/**
 * Get the leaderboard for a ranked map within a context point, paginated.
 *
 * Get the leaderboard for a ranked map within a context point by its Id, paginated.
 */
export const getContextPointRankedMapLeaderboardOptions = (options: Options<GetContextPointRankedMapLeaderboardData>) =>
  queryOptions<
    GetContextPointRankedMapLeaderboardResponse,
    DefaultError,
    GetContextPointRankedMapLeaderboardResponse,
    ReturnType<typeof getContextPointRankedMapLeaderboardQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getContextPointRankedMapLeaderboard({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getContextPointRankedMapLeaderboardQueryKey(options),
  })

export const getContextPointRankedMapLeaderboardInfiniteQueryKey = (
  options: Options<GetContextPointRankedMapLeaderboardData>,
): QueryKey<Options<GetContextPointRankedMapLeaderboardData>> =>
  createQueryKey("getContextPointRankedMapLeaderboard", options, true)

/**
 * Get the leaderboard for a ranked map within a context point, paginated.
 *
 * Get the leaderboard for a ranked map within a context point by its Id, paginated.
 */
export const getContextPointRankedMapLeaderboardInfiniteOptions = (
  options: Options<GetContextPointRankedMapLeaderboardData>,
) =>
  infiniteQueryOptions<
    GetContextPointRankedMapLeaderboardResponse,
    DefaultError,
    InfiniteData<GetContextPointRankedMapLeaderboardResponse>,
    QueryKey<Options<GetContextPointRankedMapLeaderboardData>>,
    | number
    | string
    | Pick<QueryKey<Options<GetContextPointRankedMapLeaderboardData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetContextPointRankedMapLeaderboardData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await getContextPointRankedMapLeaderboard({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: getContextPointRankedMapLeaderboardInfiniteQueryKey(options),
    },
  )

export const getMemberPointStatLeaderboardQueryKey = (options: Options<GetMemberPointStatLeaderboardData>) =>
  createQueryKey("getMemberPointStatLeaderboard", options)

/**
 * Get the guild member's leaderboard for a point within a context, paginated.
 *
 * Get the guild member's leaderboard for a point within a context by its Id, paginated.
 */
export const getMemberPointStatLeaderboardOptions = (options: Options<GetMemberPointStatLeaderboardData>) =>
  queryOptions<
    GetMemberPointStatLeaderboardResponse,
    DefaultError,
    GetMemberPointStatLeaderboardResponse,
    ReturnType<typeof getMemberPointStatLeaderboardQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMemberPointStatLeaderboard({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getMemberPointStatLeaderboardQueryKey(options),
  })

export const getMemberPointStatLeaderboardInfiniteQueryKey = (
  options: Options<GetMemberPointStatLeaderboardData>,
): QueryKey<Options<GetMemberPointStatLeaderboardData>> =>
  createQueryKey("getMemberPointStatLeaderboard", options, true)

/**
 * Get the guild member's leaderboard for a point within a context, paginated.
 *
 * Get the guild member's leaderboard for a point within a context by its Id, paginated.
 */
export const getMemberPointStatLeaderboardInfiniteOptions = (options: Options<GetMemberPointStatLeaderboardData>) =>
  infiniteQueryOptions<
    GetMemberPointStatLeaderboardResponse,
    DefaultError,
    InfiniteData<GetMemberPointStatLeaderboardResponse>,
    QueryKey<Options<GetMemberPointStatLeaderboardData>>,
    | number
    | string
    | Pick<QueryKey<Options<GetMemberPointStatLeaderboardData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetMemberPointStatLeaderboardData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await getMemberPointStatLeaderboard({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: getMemberPointStatLeaderboardInfiniteQueryKey(options),
    },
  )

export const getMemberCategoryPointStatLeaderboardQueryKey = (
  options: Options<GetMemberCategoryPointStatLeaderboardData>,
) => createQueryKey("getMemberCategoryPointStatLeaderboard", options)

/**
 * Get the guild member's leaderboard for a category point within a context, paginated.
 *
 * Get the guild member's leaderboard for a category point within a context by its Id, paginated.
 */
export const getMemberCategoryPointStatLeaderboardOptions = (
  options: Options<GetMemberCategoryPointStatLeaderboardData>,
) =>
  queryOptions<
    GetMemberCategoryPointStatLeaderboardResponse,
    DefaultError,
    GetMemberCategoryPointStatLeaderboardResponse,
    ReturnType<typeof getMemberCategoryPointStatLeaderboardQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMemberCategoryPointStatLeaderboard({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getMemberCategoryPointStatLeaderboardQueryKey(options),
  })

export const getMemberCategoryPointStatLeaderboardInfiniteQueryKey = (
  options: Options<GetMemberCategoryPointStatLeaderboardData>,
): QueryKey<Options<GetMemberCategoryPointStatLeaderboardData>> =>
  createQueryKey("getMemberCategoryPointStatLeaderboard", options, true)

/**
 * Get the guild member's leaderboard for a category point within a context, paginated.
 *
 * Get the guild member's leaderboard for a category point within a context by its Id, paginated.
 */
export const getMemberCategoryPointStatLeaderboardInfiniteOptions = (
  options: Options<GetMemberCategoryPointStatLeaderboardData>,
) =>
  infiniteQueryOptions<
    GetMemberCategoryPointStatLeaderboardResponse,
    DefaultError,
    InfiniteData<GetMemberCategoryPointStatLeaderboardResponse>,
    QueryKey<Options<GetMemberCategoryPointStatLeaderboardData>>,
    | number
    | string
    | Pick<QueryKey<Options<GetMemberCategoryPointStatLeaderboardData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetMemberCategoryPointStatLeaderboardData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await getMemberCategoryPointStatLeaderboard({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: getMemberCategoryPointStatLeaderboardInfiniteQueryKey(options),
    },
  )

export const getGuildsQueryKey = (options?: Options<GetGuildsData>) => createQueryKey("getGuilds", options)

/**
 * Get all guilds paginated
 *
 * Get all guilds in the server, with optional search and sorting.
 */
export const getGuildsOptions = (options?: Options<GetGuildsData>) =>
  queryOptions<GetGuildsResponse, DefaultError, GetGuildsResponse, ReturnType<typeof getGuildsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getGuilds({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getGuildsQueryKey(options),
  })

export const getGuildsInfiniteQueryKey = (options?: Options<GetGuildsData>): QueryKey<Options<GetGuildsData>> =>
  createQueryKey("getGuilds", options, true)

/**
 * Get all guilds paginated
 *
 * Get all guilds in the server, with optional search and sorting.
 */
export const getGuildsInfiniteOptions = (options?: Options<GetGuildsData>) =>
  infiniteQueryOptions<
    GetGuildsResponse,
    DefaultError,
    InfiniteData<GetGuildsResponse>,
    QueryKey<Options<GetGuildsData>>,
    number | string | Pick<QueryKey<Options<GetGuildsData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetGuildsData>>[0], "body" | "headers" | "path" | "query"> =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await getGuilds({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: getGuildsInfiniteQueryKey(options),
    },
  )

/**
 * Create a guild as the current player
 *
 * Create a guild as the current player using their player id from claims.
 */
export const createGuildMutation = (
  options?: Partial<Options<CreateGuildData>>,
): UseMutationOptions<CreateGuildResponse, CreateGuildError, Options<CreateGuildData>> => {
  const mutationOptions: UseMutationOptions<CreateGuildResponse, CreateGuildError, Options<CreateGuildData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await createGuild({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Delete a guild
 *
 * Delete a guild by its Id.
 */
export const deleteGuildMutation = (
  options?: Partial<Options<DeleteGuildData>>,
): UseMutationOptions<DeleteGuildResponse, DeleteGuildError, Options<DeleteGuildData>> => {
  const mutationOptions: UseMutationOptions<DeleteGuildResponse, DeleteGuildError, Options<DeleteGuildData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteGuild({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getGuildQueryKey = (options: Options<GetGuildData>) => createQueryKey("getGuild", options)

/**
 * Get a guild
 *
 * Get a specific guild by its Id.
 */
export const getGuildOptions = (options: Options<GetGuildData>) =>
  queryOptions<GetGuildResponse, GetGuildError, GetGuildResponse, ReturnType<typeof getGuildQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getGuild({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getGuildQueryKey(options),
  })

/**
 * Patch a guild
 *
 * Edit fields of a guild only by the given properties (json patch rfc6902).
 */
export const patchGuildMutation = (
  options?: Partial<Options<PatchGuildData>>,
): UseMutationOptions<PatchGuildResponse, PatchGuildError, Options<PatchGuildData>> => {
  const mutationOptions: UseMutationOptions<PatchGuildResponse, PatchGuildError, Options<PatchGuildData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await patchGuild({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getGuildExtendedQueryKey = (options: Options<GetGuildExtendedData>) =>
  createQueryKey("getGuildExtended", options)

/**
 * Get a guild with extended information
 *
 * Get a specific guild with extended information by its Id. Which includes additional fields like categories and points.
 */
export const getGuildExtendedOptions = (options: Options<GetGuildExtendedData>) =>
  queryOptions<
    GetGuildExtendedResponse,
    GetGuildExtendedError,
    GetGuildExtendedResponse,
    ReturnType<typeof getGuildExtendedQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getGuildExtended({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getGuildExtendedQueryKey(options),
  })

export const getGuildByDiscordIdQueryKey = (options: Options<GetGuildByDiscordIdData>) =>
  createQueryKey("getGuildByDiscordId", options)

/**
 * Get a guild by Discord guild ID
 *
 * Get a specific guild by its Discord guild ID.
 */
export const getGuildByDiscordIdOptions = (options: Options<GetGuildByDiscordIdData>) =>
  queryOptions<
    GetGuildByDiscordIdResponse,
    GetGuildByDiscordIdError,
    GetGuildByDiscordIdResponse,
    ReturnType<typeof getGuildByDiscordIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getGuildByDiscordId({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getGuildByDiscordIdQueryKey(options),
  })

export const lookupGuildByDiscordGuildIdQueryKey = (options: Options<LookupGuildByDiscordGuildIdData>) =>
  createQueryKey("lookupGuildByDiscordGuildId", options)

/**
 * Lookup guild ID by Discord guild ID
 *
 * Resolve a guild's ID from its linked Discord guild ID.
 */
export const lookupGuildByDiscordGuildIdOptions = (options: Options<LookupGuildByDiscordGuildIdData>) =>
  queryOptions<
    LookupGuildByDiscordGuildIdResponse,
    LookupGuildByDiscordGuildIdError,
    LookupGuildByDiscordGuildIdResponse,
    ReturnType<typeof lookupGuildByDiscordGuildIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await lookupGuildByDiscordGuildId({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: lookupGuildByDiscordGuildIdQueryKey(options),
  })

export const getMembersQueryKey = (options: Options<GetMembersData>) => createQueryKey("getMembers", options)

/**
 * Get all members of a guild.
 *
 * Get all members of a guild by guild id.
 */
export const getMembersOptions = (options: Options<GetMembersData>) =>
  queryOptions<GetMembersResponse, DefaultError, GetMembersResponse, ReturnType<typeof getMembersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMembers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getMembersQueryKey(options),
  })

export const getMembersInfiniteQueryKey = (options: Options<GetMembersData>): QueryKey<Options<GetMembersData>> =>
  createQueryKey("getMembers", options, true)

/**
 * Get all members of a guild.
 *
 * Get all members of a guild by guild id.
 */
export const getMembersInfiniteOptions = (options: Options<GetMembersData>) =>
  infiniteQueryOptions<
    GetMembersResponse,
    DefaultError,
    InfiniteData<GetMembersResponse>,
    QueryKey<Options<GetMembersData>>,
    number | string | Pick<QueryKey<Options<GetMembersData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetMembersData>>[0], "body" | "headers" | "path" | "query"> =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await getMembers({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: getMembersInfiniteQueryKey(options),
    },
  )

/**
 * Join a guild as the current player.
 *
 * Join a guild as the current player using their player id from claims.
 */
export const joinGuildAtMeMutation = (
  options?: Partial<Options<JoinGuildAtMeData>>,
): UseMutationOptions<JoinGuildAtMeResponse, JoinGuildAtMeError, Options<JoinGuildAtMeData>> => {
  const mutationOptions: UseMutationOptions<JoinGuildAtMeResponse, JoinGuildAtMeError, Options<JoinGuildAtMeData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await joinGuildAtMe({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getMemberQueryKey = (options: Options<GetMemberData>) => createQueryKey("getMember", options)

/**
 * Get a member of a guild
 *
 * Get a member of a guild by player id.
 */
export const getMemberOptions = (options: Options<GetMemberData>) =>
  queryOptions<GetMemberResponse, GetMemberError, GetMemberResponse, ReturnType<typeof getMemberQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMember({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getMemberQueryKey(options),
  })

/**
 * Join a guild
 *
 * Join a guild by player id.
 */
export const joinGuildMutation = (
  options?: Partial<Options<JoinGuildData>>,
): UseMutationOptions<JoinGuildResponse, JoinGuildError, Options<JoinGuildData>> => {
  const mutationOptions: UseMutationOptions<JoinGuildResponse, JoinGuildError, Options<JoinGuildData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await joinGuild({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getMemberLevelStatsQueryKey = (options: Options<GetMemberLevelStatsData>) =>
  createQueryKey("getMemberLevelStats", options)

/**
 * Get level stats for a guild member.
 *
 * Get level statistics for a specific player within a context.
 */
export const getMemberLevelStatsOptions = (options: Options<GetMemberLevelStatsData>) =>
  queryOptions<
    GetMemberLevelStatsResponse,
    DefaultError,
    GetMemberLevelStatsResponse,
    ReturnType<typeof getMemberLevelStatsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMemberLevelStats({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getMemberLevelStatsQueryKey(options),
  })

export const getCurrentMemberLevelStatsQueryKey = (options: Options<GetCurrentMemberLevelStatsData>) =>
  createQueryKey("getCurrentMemberLevelStats", options)

/**
 * Get level stats for the current authenticated member.
 *
 * Get level statistics for the current authenticated player within a context.
 */
export const getCurrentMemberLevelStatsOptions = (options: Options<GetCurrentMemberLevelStatsData>) =>
  queryOptions<
    GetCurrentMemberLevelStatsResponse,
    DefaultError,
    GetCurrentMemberLevelStatsResponse,
    ReturnType<typeof getCurrentMemberLevelStatsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCurrentMemberLevelStats({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getCurrentMemberLevelStatsQueryKey(options),
  })

export const getMemberContextStatsQueryKey = (options: Options<GetMemberContextStatsData>) =>
  createQueryKey("getMemberContextStats", options)

/**
 * Get context stats for a guild member.
 *
 * Get context statistics for a specific player within a context.
 */
export const getMemberContextStatsOptions = (options: Options<GetMemberContextStatsData>) =>
  queryOptions<
    GetMemberContextStatsResponse,
    GetMemberContextStatsError,
    GetMemberContextStatsResponse,
    ReturnType<typeof getMemberContextStatsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMemberContextStats({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getMemberContextStatsQueryKey(options),
  })

export const getCurrentMemberContextStatsQueryKey = (options: Options<GetCurrentMemberContextStatsData>) =>
  createQueryKey("getCurrentMemberContextStats", options)

/**
 * Get context stats for the current authenticated member.
 *
 * Get context statistics for the current authenticated player within a context.
 */
export const getCurrentMemberContextStatsOptions = (options: Options<GetCurrentMemberContextStatsData>) =>
  queryOptions<
    GetCurrentMemberContextStatsResponse,
    GetCurrentMemberContextStatsError,
    GetCurrentMemberContextStatsResponse,
    ReturnType<typeof getCurrentMemberContextStatsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCurrentMemberContextStats({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getCurrentMemberContextStatsQueryKey(options),
  })

export const getLevelsQueryKey = (options: Options<GetLevelsData>) => createQueryKey("getLevels", options)

/**
 * Get all levels in a context, optionally filtered by category.
 *
 * - No parameters: Returns all levels.
 * - hasCategory=false: Returns levels with no category.
 * - category=5: Returns levels in category 5.
 */
export const getLevelsOptions = (options: Options<GetLevelsData>) =>
  queryOptions<GetLevelsResponse, DefaultError, GetLevelsResponse, ReturnType<typeof getLevelsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getLevels({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getLevelsQueryKey(options),
  })

export const getGuildStatsQueryKey = (options: Options<GetGuildStatsData>) => createQueryKey("getGuildStats", options)

/**
 * Get the statistics of the guild by guild id.
 *
 * Get the statistics of the guild by guild id.
 */
export const getGuildStatsOptions = (options: Options<GetGuildStatsData>) =>
  queryOptions<
    GetGuildStatsResponse,
    GetGuildStatsError,
    GetGuildStatsResponse,
    ReturnType<typeof getGuildStatsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getGuildStats({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getGuildStatsQueryKey(options),
  })

export const getCategoriesPaginatedQueryKey = (options?: Options<GetCategoriesPaginatedData>) =>
  createQueryKey("getCategoriesPaginated", options)

/**
 * Get all categories paginated.
 *
 * Get all categories in the server.
 */
export const getCategoriesPaginatedOptions = (options?: Options<GetCategoriesPaginatedData>) =>
  queryOptions<
    GetCategoriesPaginatedResponse,
    DefaultError,
    GetCategoriesPaginatedResponse,
    ReturnType<typeof getCategoriesPaginatedQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCategoriesPaginated({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getCategoriesPaginatedQueryKey(options),
  })

export const getCategoriesPaginatedInfiniteQueryKey = (
  options?: Options<GetCategoriesPaginatedData>,
): QueryKey<Options<GetCategoriesPaginatedData>> => createQueryKey("getCategoriesPaginated", options, true)

/**
 * Get all categories paginated.
 *
 * Get all categories in the server.
 */
export const getCategoriesPaginatedInfiniteOptions = (options?: Options<GetCategoriesPaginatedData>) =>
  infiniteQueryOptions<
    GetCategoriesPaginatedResponse,
    DefaultError,
    InfiniteData<GetCategoriesPaginatedResponse>,
    QueryKey<Options<GetCategoriesPaginatedData>>,
    number | string | Pick<QueryKey<Options<GetCategoriesPaginatedData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetCategoriesPaginatedData>>[0], "body" | "headers" | "path" | "query"> =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await getCategoriesPaginated({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: getCategoriesPaginatedInfiniteQueryKey(options),
    },
  )

export const getCategoryQueryKey = (options: Options<GetCategoryData>) => createQueryKey("getCategory", options)

/**
 * Get a category.
 *
 * Get a category in the server by its Id.
 */
export const getCategoryOptions = (options: Options<GetCategoryData>) =>
  queryOptions<GetCategoryResponse, GetCategoryError, GetCategoryResponse, ReturnType<typeof getCategoryQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCategory({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getCategoryQueryKey(options),
  })

export const getCategoriesQueryKey = (options: Options<GetCategoriesData>) => createQueryKey("getCategories", options)

/**
 * Get all categories of a guild.
 *
 * Get all categories of a guild by guild id.
 */
export const getCategoriesOptions = (options: Options<GetCategoriesData>) =>
  queryOptions<GetCategoriesResponse, DefaultError, GetCategoriesResponse, ReturnType<typeof getCategoriesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCategories({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getCategoriesQueryKey(options),
  })

/**
 * Create a category for a guild.
 *
 * Create a category for a guild by its Id.
 */
export const createCategoryMutation = (
  options?: Partial<Options<CreateCategoryData>>,
): UseMutationOptions<CreateCategoryResponse, CreateCategoryError, Options<CreateCategoryData>> => {
  const mutationOptions: UseMutationOptions<
    CreateCategoryResponse,
    CreateCategoryError,
    Options<CreateCategoryData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createCategory({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Delete a category of a guild.
 *
 * Delete a category of a guild by its Id.
 */
export const deleteCategoryMutation = (
  options?: Partial<Options<DeleteCategoryData>>,
): UseMutationOptions<DeleteCategoryResponse, DeleteCategoryError, Options<DeleteCategoryData>> => {
  const mutationOptions: UseMutationOptions<
    DeleteCategoryResponse,
    DeleteCategoryError,
    Options<DeleteCategoryData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteCategory({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Update a category of a guild.
 *
 * Update a category of a guild by its Id.
 */
export const updateCategoryMutation = (
  options?: Partial<Options<UpdateCategoryData>>,
): UseMutationOptions<UpdateCategoryResponse, DefaultError, Options<UpdateCategoryData>> => {
  const mutationOptions: UseMutationOptions<UpdateCategoryResponse, DefaultError, Options<UpdateCategoryData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateCategory({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Import ranked maps from old GuildSaber
 *
 * Import ranked maps from old GuildSaber for a specific guild.
 */
export const importOldGuildSaberMapsBackgroundMutation = (
  options?: Partial<Options<ImportOldGuildSaberMapsBackgroundData>>,
): UseMutationOptions<
  ImportOldGuildSaberMapsBackgroundResponse,
  ImportOldGuildSaberMapsBackgroundError,
  Options<ImportOldGuildSaberMapsBackgroundData>
> => {
  const mutationOptions: UseMutationOptions<
    ImportOldGuildSaberMapsBackgroundResponse,
    ImportOldGuildSaberMapsBackgroundError,
    Options<ImportOldGuildSaberMapsBackgroundData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await importOldGuildSaberMapsBackground({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Enqueue BeatLeader player scores import.
 *
 * Queues a background task to import all scores for the specified player from BeatLeader.
 */
export const postDebugImportBeatleaderScoresByPlayerIdMutation = (
  options?: Partial<Options<PostDebugImportBeatleaderScoresByPlayerIdData>>,
): UseMutationOptions<
  unknown,
  PostDebugImportBeatleaderScoresByPlayerIdError,
  Options<PostDebugImportBeatleaderScoresByPlayerIdData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    PostDebugImportBeatleaderScoresByPlayerIdError,
    Options<PostDebugImportBeatleaderScoresByPlayerIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postDebugImportBeatleaderScoresByPlayerId({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Enqueue ScoreSaber player scores import.
 *
 * Queues a background task to import all scores for the specified player from ScoreSaber.
 */
export const postDebugImportScoresaberScoresByPlayerIdMutation = (
  options?: Partial<Options<PostDebugImportScoresaberScoresByPlayerIdData>>,
): UseMutationOptions<
  unknown,
  PostDebugImportScoresaberScoresByPlayerIdError,
  Options<PostDebugImportScoresaberScoresByPlayerIdData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    PostDebugImportScoresaberScoresByPlayerIdError,
    Options<PostDebugImportScoresaberScoresByPlayerIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postDebugImportScoresaberScoresByPlayerId({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Remove all scores from the database.
 *
 * Deletes all ranked scores from the database. USE WITH CAUTION!
 */
export const postDebugRemoveAllScoresMutation = (
  options?: Partial<Options<PostDebugRemoveAllScoresData>>,
): UseMutationOptions<unknown, DefaultError, Options<PostDebugRemoveAllScoresData>> => {
  const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostDebugRemoveAllScoresData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await postDebugRemoveAllScores({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Remove all ranked scores from the database.
 *
 * Deletes all ranked scores from the database. USE WITH CAUTION!
 */
export const postDebugRemoveAllRankedScoresMutation = (
  options?: Partial<Options<PostDebugRemoveAllRankedScoresData>>,
): UseMutationOptions<unknown, DefaultError, Options<PostDebugRemoveAllRankedScoresData>> => {
  const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostDebugRemoveAllRankedScoresData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await postDebugRemoveAllRankedScores({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Remove all ranked maps from the database.
 *
 * Deletes all ranked maps from the database. USE WITH CAUTION!
 */
export const postDebugRemoveAllRankedMapsMutation = (
  options?: Partial<Options<PostDebugRemoveAllRankedMapsData>>,
): UseMutationOptions<unknown, DefaultError, Options<PostDebugRemoveAllRankedMapsData>> => {
  const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostDebugRemoveAllRankedMapsData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await postDebugRemoveAllRankedMaps({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Recalculate member points for a player.
 *
 * Recalculates member points for all contexts the player is a member of.
 */
export const postDebugRecalculateMemberPointsByPlayerIdMutation = (
  options?: Partial<Options<PostDebugRecalculateMemberPointsByPlayerIdData>>,
): UseMutationOptions<unknown, DefaultError, Options<PostDebugRecalculateMemberPointsByPlayerIdData>> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DefaultError,
    Options<PostDebugRecalculateMemberPointsByPlayerIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postDebugRecalculateMemberPointsByPlayerId({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Recalculate member levels for a player.
 *
 * Recalculates member levels for all contexts the player is a member of.
 */
export const postDebugRecalculateMemberLevelsByPlayerIdMutation = (
  options?: Partial<Options<PostDebugRecalculateMemberLevelsByPlayerIdData>>,
): UseMutationOptions<unknown, DefaultError, Options<PostDebugRecalculateMemberLevelsByPlayerIdData>> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DefaultError,
    Options<PostDebugRecalculateMemberLevelsByPlayerIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postDebugRecalculateMemberLevelsByPlayerId({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Recalculate player scores.
 *
 * Recalculates all player scores for the specified player.
 */
export const postDebugRecalculatePlayerScoresByPlayerIdMutation = (
  options?: Partial<Options<PostDebugRecalculatePlayerScoresByPlayerIdData>>,
): UseMutationOptions<unknown, DefaultError, Options<PostDebugRecalculatePlayerScoresByPlayerIdData>> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DefaultError,
    Options<PostDebugRecalculatePlayerScoresByPlayerIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postDebugRecalculatePlayerScoresByPlayerId({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Delete all member point stats for a player.
 *
 * Deletes all member point stats for the specified player. USE WITH CAUTION!
 */
export const postDebugDeleteMemberPointStatsByPlayerIdMutation = (
  options?: Partial<Options<PostDebugDeleteMemberPointStatsByPlayerIdData>>,
): UseMutationOptions<unknown, DefaultError, Options<PostDebugDeleteMemberPointStatsByPlayerIdData>> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DefaultError,
    Options<PostDebugDeleteMemberPointStatsByPlayerIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postDebugDeleteMemberPointStatsByPlayerId({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const beatLeaderLoginQueryKey = (options?: Options<BeatLeaderLoginData>) =>
  createQueryKey("beatLeaderLogin", options)

/**
 * Login with BeatLeader
 *
 * Initiate the BeatLeader authentication flow with optional callback path.
 */
export const beatLeaderLoginOptions = (options?: Options<BeatLeaderLoginData>) =>
  queryOptions<unknown, DefaultError, unknown, ReturnType<typeof beatLeaderLoginQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await beatLeaderLogin({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: beatLeaderLoginQueryKey(options),
  })

export const discordLoginQueryKey = (options?: Options<DiscordLoginData>) => createQueryKey("discordLogin", options)

/**
 * Login with Discord
 *
 * Initiate the Discord authentication flow with optional callback path.
 */
export const discordLoginOptions = (options?: Options<DiscordLoginData>) =>
  queryOptions<unknown, DefaultError, unknown, ReturnType<typeof discordLoginQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await discordLogin({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: discordLoginQueryKey(options),
  })

export const discordLinkQueryKey = (options?: Options<DiscordLinkData>) => createQueryKey("discordLink", options)

/**
 * Initiate linking Discord from authentication flow.
 *
 * Initiate the Discord authentication flow to link Discord account to an existing authenticated user with optional callback path.
 */
export const discordLinkOptions = (options?: Options<DiscordLinkData>) =>
  queryOptions<unknown, DefaultError, unknown, ReturnType<typeof discordLinkQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await discordLink({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: discordLinkQueryKey(options),
  })

export const discordLinkCallbackQueryKey = (options?: Options<DiscordLinkCallbackData>) =>
  createQueryKey("discordLinkCallback", options)

/**
 * Link Discord account to existing authenticated user.
 *
 * Handles the callback from Discord to link Discord account to existing authenticated user.
 */
export const discordLinkCallbackOptions = (options?: Options<DiscordLinkCallbackData>) =>
  queryOptions<
    DiscordLinkCallbackResponse,
    DiscordLinkCallbackError,
    DiscordLinkCallbackResponse,
    ReturnType<typeof discordLinkCallbackQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await discordLinkCallback({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: discordLinkCallbackQueryKey(options),
  })

export const discordLinkCallbackWithRedirectQueryKey = (options: Options<DiscordLinkCallbackWithRedirectData>) =>
  createQueryKey("discordLinkCallbackWithRedirect", options)

/**
 * Link Discord account to existing authenticated user with redirect.
 *
 * Handles the callback from Discord after authentication to link Discord account to an existing authenticated user and redirects to a specified path from the calling origin with ?type=discordLink&{error}&status as query params.
 */
export const discordLinkCallbackWithRedirectOptions = (options: Options<DiscordLinkCallbackWithRedirectData>) =>
  queryOptions<
    DiscordLinkCallbackWithRedirectResponse,
    DiscordLinkCallbackWithRedirectError,
    DiscordLinkCallbackWithRedirectResponse,
    ReturnType<typeof discordLinkCallbackWithRedirectQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await discordLinkCallbackWithRedirect({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: discordLinkCallbackWithRedirectQueryKey(options),
  })

export const beatLeaderCallbackQueryKey = (options?: Options<BeatLeaderCallbackData>) =>
  createQueryKey("beatLeaderCallback", options)

/**
 * Get session token after authenticating with BeatLeader.
 *
 * Handles the callback from BeatLeader after authentication and returns a token.
 */
export const beatLeaderCallbackOptions = (options?: Options<BeatLeaderCallbackData>) =>
  queryOptions<
    BeatLeaderCallbackResponse,
    BeatLeaderCallbackError,
    BeatLeaderCallbackResponse,
    ReturnType<typeof beatLeaderCallbackQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await beatLeaderCallback({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: beatLeaderCallbackQueryKey(options),
  })

export const discordCallbackQueryKey = (options?: Options<DiscordCallbackData>) =>
  createQueryKey("discordCallback", options)

/**
 * Get session token after authenticating with Discord.
 *
 * Handles the callback from Discord after authentication and returns a token.
 */
export const discordCallbackOptions = (options?: Options<DiscordCallbackData>) =>
  queryOptions<
    DiscordCallbackResponse,
    DiscordCallbackError,
    DiscordCallbackResponse,
    ReturnType<typeof discordCallbackQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await discordCallback({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: discordCallbackQueryKey(options),
  })

export const discordCallbackWithRedirectQueryKey = (options: Options<DiscordCallbackWithRedirectData>) =>
  createQueryKey("discordCallbackWithRedirect", options)

/**
 * Redirect with session token or error after Discord authentication.
 *
 * Handles the callback from Discord after authentication and redirects to a specified path from the calling origin with ?type=auth&{token/error}&status as query params.
 */
export const discordCallbackWithRedirectOptions = (options: Options<DiscordCallbackWithRedirectData>) =>
  queryOptions<
    DiscordCallbackWithRedirectResponse,
    DiscordCallbackWithRedirectError,
    DiscordCallbackWithRedirectResponse,
    ReturnType<typeof discordCallbackWithRedirectQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await discordCallbackWithRedirect({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: discordCallbackWithRedirectQueryKey(options),
  })

export const beatLeaderCallbackWithRedirectQueryKey = (options: Options<BeatLeaderCallbackWithRedirectData>) =>
  createQueryKey("beatLeaderCallbackWithRedirect", options)

/**
 * Redirect with session token or error after BeatLeader authentication.
 *
 * Handles the callback from BeatLeader after authentication and redirects to a specified path from the calling origin with ?type=auth&{token/error}&status as query params.
 */
export const beatLeaderCallbackWithRedirectOptions = (options: Options<BeatLeaderCallbackWithRedirectData>) =>
  queryOptions<
    BeatLeaderCallbackWithRedirectResponse,
    BeatLeaderCallbackWithRedirectError,
    BeatLeaderCallbackWithRedirectResponse,
    ReturnType<typeof beatLeaderCallbackWithRedirectQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await beatLeaderCallbackWithRedirect({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: beatLeaderCallbackWithRedirectQueryKey(options),
  })

/**
 * Log out the current user by invalidating their session.
 */
export const logoutMutation = (
  options?: Partial<Options<LogoutData>>,
): UseMutationOptions<LogoutResponse, LogoutError, Options<LogoutData>> => {
  const mutationOptions: UseMutationOptions<LogoutResponse, LogoutError, Options<LogoutData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await logout({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Log out the current user from all sessions by invalidating all their sessions.
 */
export const logoutAllMutation = (
  options?: Partial<Options<LogoutAllData>>,
): UseMutationOptions<LogoutAllResponse, LogoutAllError, Options<LogoutAllData>> => {
  const mutationOptions: UseMutationOptions<LogoutAllResponse, LogoutAllError, Options<LogoutAllData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await logoutAll({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const logoutWithRedirectQueryKey = (options: Options<LogoutWithRedirectData>) =>
  createQueryKey("logoutWithRedirect", options)

/**
 * Log out the current user by invalidating their session and redirecting.
 */
export const logoutWithRedirectOptions = (options: Options<LogoutWithRedirectData>) =>
  queryOptions<unknown, DefaultError, unknown, ReturnType<typeof logoutWithRedirectQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await logoutWithRedirect({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: logoutWithRedirectQueryKey(options),
  })

export const logoutAllWithRedirectQueryKey = (options: Options<LogoutAllWithRedirectData>) =>
  createQueryKey("logoutAllWithRedirect", options)

/**
 * Log out the current user from all sessions by invalidating all their sessions and redirecting.
 */
export const logoutAllWithRedirectOptions = (options: Options<LogoutAllWithRedirectData>) =>
  queryOptions<unknown, DefaultError, unknown, ReturnType<typeof logoutAllWithRedirectQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await logoutAllWithRedirect({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: logoutAllWithRedirectQueryKey(options),
  })
